- m3-sys/cminstall/src/config-no-install/Darwin.common
and modern assemblers error for them.
> Disable stabs on Darwin. There is no debugger to read them

- m3-sys/m3tests/src/m3makefile
- m3-sys/m3tests/src/p2/p268/Main.m3
- m3-sys/m3tests/src/p2/p268/m3makefile
Bug is not yet understood/fixed, but it works for gcc backend at least (and integrated?)
This is derived from m3-comm/sharedobjgen.
> Add test that fails in Grisu when using C backend.

- m3-sys/m3back/src/M3C.m3
There are special things in the setjmp (and longjmp?) declaration,
best duplicated by actually including setjmp.h.
A later change will only include setjmp.h in files that
call setjmp, or longjmp, or maybe that declare local jmp_buf.
i.e. to not slow down compilation as much.
> Fix AMD64_NT exception handling.

- m3-sys/cminstall/src/config-no-install/NT.common
TODO: autodetect?
The environment variable CM3_VS2015_OR_NEWER can be 0 or 1 or not defined.
Not defined defaults to 1.
Use 0 for older toolsets/runtimes.
The change is a bit overkill.
You can just set CM3_VS2015_OR_NEWER=1 or VS2015_OR_NEWER in cm3 for a long time now.
Also do not require $USE_MSVCRT be 0 or 1 unless USE_MSVCRT is not defined.
> Default to Visual C++ 2015 or newer, for purposes of linking to C runtime.

- caltech-other/newuoa/src/m3makefile
without error (does nothing) on other platforms, such as amd64_nt.
> caltech-other/newuoa/m3makefile: Move library() to within if amd64_linux so it builds/ships

- m3-libs/m3core/src/m3makefile
The .i3 there can be useful, for example to build
mklib on other hosts.
This effectively undoes commit 997e499081 from year 2014.
This originally went in commit 907515e97f in year 2008.
Frontend accepts all the Win32 calling conventions,
silently ignoring them on most platforms.
> m3core: Build Win32 for all targets.

- m3-sys/m3cc/gcc-4.7/gcc/ira-build.c
- m3-sys/m3cc/gcc-4.7/gcc/ira-color.c
- m3-sys/m3cc/gcc-4.7/gcc/ira-conflicts.c
- m3-sys/m3cc/gcc-4.7/gcc/ira-costs.c
- m3-sys/m3cc/gcc-4.7/gcc/ira-emit.c
- m3-sys/m3cc/gcc-4.7/gcc/ira-lives.c
- m3-sys/m3cc/gcc-4.7/gcc/ira.c
cm3cg crashes e.g. in caltech*/cit-util.
Ues pragma gcc optimize O1 to downgrade from O2 to workaround.
More debugging would be good.
> m3cc: Optimize gcc register allocator less to avoid Linux/x86 crashes.

- m3-sys/m3cc/gcc-4.7/gcc/builtins.c
- m3-sys/m3cc/gcc-4.7/gcc/configure
- m3-sys/m3cc/gcc-4.7/gcc/configure.ac
- m3-sys/m3cc/gcc-4.7/gcc/gengtype.c
- m3-sys/m3cc/gcc-4.7/gcc/gengtype.h
- m3-sys/m3cc/gcc-4.7/gcc/system.h
- m3-sys/m3cc/gcc-4.7/include/ansidecl.h
- m3-sys/m3cc/gcc-4.7/libcpp/configure
- m3-sys/m3cc/gcc-4.7/libiberty/configure
m3cc: Reduce warnings building m3cc.
- Remove -pedantic more/better/cleaner (probably same amount).
- Convert some if undefined to if 0 or 1.
- Remove unused static function.
> m3cc: Reduce warnings building m3cc.

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.i3
- m3-libs/m3core/src/coroutine/UCONTEXT/CoroutineUcontext.m3
The function ContextC__PushContext is not convincing.
The memset is inefficient, and can be completely optimized away.
Intent is probably to do alloca(256) here.
Clean it up a little.
Try to accomodate stacks that grow up.
i.e. HPPA, but that is not tested (I might have
tested it long ago with the Posix threads).
include m3core.h
Use size_t instead of unsigned long; or rather, whatever m3core.h does
Fix mild printf problems %p vs. %lx.
Cast to correct pointer type instead of void*.
Do not use auto, at least under if cplusplus.
Add extern C (maybe some day remove it)
> m3core: Convert coroutine code to valid C++.

- m3-sys/cminstall/src/config-no-install/AMD64_NT
I and another are getting sharing violations.
Investigate at a much later time or never.
(bulk cl will help, possibly with /MP)
This reverts ce2d23fdaf6743b2bc63db15a3bd68f48664d380
> config: Undo AMD64_NT parallel back.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3middle/src/Target.m3
- Avoid include setjmp.h unless call seen to setjmp, or
less likely, longjmp. This should be a little faster.
- Handle the VMS setjmp name.
- Cast first parameter to setjmp tp *(jmpbuf*) to fix C++ compilation.
- setjmp instead of _setjmp on nascent ARM64_NT
- some comments
This enables the AMD64_LINUX system to be build using the C backend, compiled as C++.
The real problem being passing char* to setjmp.
> C backend setjmp work:

- caltech-other/voronoi/src/defs.h
Forward declare structs so that function declarations do not introduce private structs.
> caltech: More C++ fixes.

- m3-libs/m3core/src/win32/WinBase.i3
This is not the -1 vs. UINT32 problem, this is just
other mistakes I noticed, i.e. HeapAlloc and affinity and stack size.
> Win32: Widen some parameters from UINT32 to SIZE_T.

- m3-libs/m3core/src/win32/WinBase.i3
- m3-libs/m3core/src/win32/WinSock.i3
Win64: Widen some UINT32 parameters to UINT32_ARG = INTEGER
so that 64bit systems can pass -1 or other seemingly invalid but acceptable values.
ExitProcess because people pass -1.
TerminateProcess because it is like ExitProcess.
And ioctlsocket because it has been a problem.
Quite possibly we want to do this more.
On NT/amd64 parameters are never passed in half registers,
or half stack positions. Always 64bits per parameter.
So this is safe.
It does not work for out pointer/var parameters however.
This fixes e.g.:
```
C:\s\cm3\scripts\python>boot1.py PA32_HPUX c
== package C:\s\cm3\m3-libs\m3core ==
+++ C:\cm3\bin\cm3.exe  -DM3_BACKEND_MODE=C   -build -override -DROOT=C:/s/cm3 -boot -no-m3ship-resolution -group-writable -keep -DM3CC_TARGET=PA32_HPUX +++
--- building in PA32_HPUXc --- …
```
> Win64: Widen some UINT32 parameters to INTEGER.

- m3-sys/cminstall/src/config-no-install/VMS.common
cd C:\s\cm3\m3-sys\cminstall\src\config-no-install
findstr TARGET_ENDIAN AL* vms*
Alpha32.common:readonly TARGET_ENDIAN = "LITTLE" % { "BIG" OR "LITTLE" }
Alpha64.common:readonly TARGET_ENDIAN = "LITTLE" % { "BIG" OR "LITTLE" }
ALPHA_OSF:readonly TARGET_ENDIAN = "LITTLE" % { "BIG" OR "LITTLE" }
VMS.common:readonly TARGET_ENDIAN = "LITTLE"
This fails because cannot write to readonly variable.
Quake should allow it, maybe, since writing the same value it already has.
But for now, just remove the last line.
Arguably it doesn't belong there, or even where it is.
Arguably it is a function of the root config, in case
of architectures like ARM, PowerPC, MIPS whose endianness varies.
Ideally we remove endian sensitivity from the system, really.
> Config: Fix Alpha VMS builds.

- m3-libs/libm3/src/os/POSIX/m3makefile
- m3-libs/m3core/src/runtime/POSIX/RTSignalC.c
- m3-sys/cminstall/src/config-no-install/RISCV64.common
- m3-sys/cminstall/src/config-no-install/RISCV64_LINUX
- m3-sys/m3middle/src/Target.m3
- scripts/python/pylib.py
System can build itself.
Using the C backend as usual.
If using qemu, you must use qemu-system, not merely qemu usermode/chroot/binfmt on top of native kernel, because of preemptive suspend. And this is much slower, alas.
> RISCV64_LINUX support.

- caltech-other/bool/src/bool.c
- caltech-other/bool/src/bool.h
- caltech-other/bool/src/misc.c
- caltech-other/bool/src/misc.h
- caltech-other/m3readline/c/src/program.c
- caltech-other/voronoi/src/defs.c
- caltech-other/voronoi/src/defs.h
- caltech-other/voronoi/src/edgelist.c
- caltech-other/voronoi/src/geometry.c
- caltech-other/voronoi/src/heap.c
- caltech-other/voronoi/src/main.c
- caltech-other/voronoi/src/mod3_main.c
- caltech-other/voronoi/src/mymalloc.c
- caltech-other/voronoi/src/output.c
- caltech-other/voronoi/src/voronoi.c
- typedef struct foo foo and then refer to just foo
- () to (void)
- Some space and newline changes but not huge/systematic.
- Remove extern on functions, it is redundant.
- unsigned long to size_t for hypothetical portability
to more environments, mainly Win64; many would argue
for uintptr_t but same thing really.
- Remove semicolons after close braces.
> caltech-other: Cleanup.

- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
It was already always variable false.
There is a missed optimization here, but it is ok.
> m3middle: Make Aligned_procedures constant false.

- m3-libs/libm3/src/sequence/m3makefile
- m3-sys/m3front/src/misc/Scanner.i3
- m3-sys/m3front/src/misc/Scanner.m3
- m3-sys/m3front/src/stmts/AssertStmt.m3
- m3-sys/m3tests/src/m3makefile
- m3-sys/m3tests/src/r0/r005/Main.m3
- m3-sys/m3tests/src/r0/r005/m3makefile
- m3-sys/m3tests/src/r0/r005/stderr.pgm
Previously:
```
***
*** runtime error:
***    <*ASSERT*> failed.
***    file "..\Main.m3", line 4
***
```
Now:
```
***
*** runtime error:
***    <*ASSERT*> failed: 1 = 22
***    file "..\Main.m3", line 4
***
```
This is presently on unconditionally, but some configurability
and/or moving the text out of the program, might be desirable.
(This probably also breaks bootstrapping from existing libm3. New release should be issued.)
> Include expressions in assertion failures.

- m3-libs/libm3/src/os/POSIX/SocketPosix.i3
- m3-libs/libm3/src/os/POSIX/SocketPosix.m3
- m3-libs/libm3/src/os/POSIX/SocketPosixC.c
- m3-libs/libm3/src/os/POSIX/m3makefile
libm3: Move the OSF/Ultrix RefetchError hack into ifdef'ed C, in order to converge on identical C code for all targets. (or at least cut the matrix to small). We should probably just cut support for these very old systems.
> libm3: Move the OSF/Ultrix RefetchError hack into C.

- m3-comm/tcp/src/WIN32/IP.m3
The relevant functions are all documented as using thread locals on Windows.
Some Unix systems "need" this locking, some do not.
It does not suffice on systems that "need" it, because
other threads in the process might not share this lock.
> Win32 IP.m3: Remove unnecessary locking.

- m3-libs/m3core/src/unix/Common/Unetdb.i3
It is not used.
It is not thread safe on Windows (it is a small inline
function in the headers, that can be copy/pasted and fixed).
Any future use imho should be in C, not Modula-3.
i.e. Prefer to stop rewriting /usr/include.
Also this declaration might not work on Windows.
It looks correct, but the function is inline in .h files,
so might not link.
> m3core: Remove declaration of gai_strerror.

- m3-win/import-libs/src/m3makefile
- scripts/all-deps
- scripts/make-dist.sh
- scripts/pkginfo.txt
- scripts/win/upgrade.cmd
> import-libs: Remove from scripts and make building it just print a warning.

- m3-libs/m3core/src/unix/Common/Uconstants.c
> m3core: It is mildly useful to depend on error values to be non-zero.

- m3-comm/tcp/src/POSIX/TCPHack.m3
- m3-comm/tcp/src/POSIX/TCPHackC.c
- m3-comm/tcp/src/POSIX/TCPHackNull.m3
- m3-comm/tcp/src/POSIX/m3makefile
- m3-libs/libm3/src/os/POSIX/SocketPosixC.c
This is OSF/1 and Ultrix specific code, that can/should probably just be deleted.
(If you want to run MIPS or Alpha, try another OS.)
> m3-comm: Move TCPHack from Modula-3 to ifdefed C.

- m3-libs/m3core/src/m3core.h
These might be useful in future.
I was going to use them, but then decided to limit C interaction
with traced references, lest barriers are needed. i.e. with mutexes.
> m3core.h: Add __try/__finally macros that do nothing for non-msc.

- m3-sys/cminstall/src/config-no-install/AMD64_NT
We should remove libcmt.lib support by now, since it was
just an ancient aberrant toolset that lacked C runtime .dll,
and some bug workaround here, that I never debugged, just
tried it again and it worked.
> AMD64_NT: Switch from libcmt.lib to C runtime .dll by default.

- caltech-parser/cit_util/src/m3makefile
this in libm3 too. This highlights Modula-3 generic
deficiencies vs. C++ alas.
> caltech: Remove duplicate SeqChar since I did this

- m3-sys/cminstall/src/config-no-install/ALPHA_LINUX
- m3-sys/cminstall/src/config-no-install/ALPHA_OPENBSD
- m3-sys/cminstall/src/config-no-install/AMD64_FREEBSD
- m3-sys/cminstall/src/config-no-install/AMD64_LINUX
- m3-sys/cminstall/src/config-no-install/AMD64_NETBSD
- m3-sys/cminstall/src/config-no-install/AMD64_OPENBSD
- m3-sys/cminstall/src/config-no-install/ARM_LINUX.common
- m3-sys/cminstall/src/config-no-install/Darwin.common
- m3-sys/cminstall/src/config-no-install/I386_FREEBSD.common
- m3-sys/cminstall/src/config-no-install/I386_LINUX.common
- m3-sys/cminstall/src/config-no-install/I386_NETBSD
- m3-sys/cminstall/src/config-no-install/I386_OPENBSD
- m3-sys/cminstall/src/config-no-install/NT.common
- m3-sys/cminstall/src/config-no-install/PA32_HPUX
- m3-sys/cminstall/src/config-no-install/PPC32_OPENBSD
- m3-sys/cminstall/src/config-no-install/PPC_LINUX
- m3-sys/cminstall/src/config-no-install/SPARC32_LINUX
- m3-sys/cminstall/src/config-no-install/SPARC64_LINUX
- m3-sys/cminstall/src/config-no-install/SPARC64_OPENBSD
- m3-sys/cminstall/src/config-no-install/Solaris.common
- m3-sys/cminstall/src/config/FreeBSD3
- m3-sys/cminstall/src/config/HPPA
- m3-sys/cminstall/src/config/IBMR2
- m3-sys/cminstall/src/config/IRIX5
- m3-sys/cminstall/src/config/LINUXELF
- m3-sys/cminstall/src/config/SPARC
Config: gcc/gdb -gstabs and -gstabs+ is buggy.
gdb shows incorrect information.
Use plain -g for compiling C.
This does not change m3cc/cm3cg command lines.
This does change linking command lines, but it does not appear to matter.
-gstabs was never really well motivated here anyway.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99457
> Config: gcc/gdb -gstabs and -gstabs+ is buggy.

- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
- m3-sys/m3middle/src/TargetT.i3
It was already always true.
Add comments belaboring its meaning.
> m3middle: Make PCC_bitfield_type_matters constant instead of variable.

- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
This breaks only VAX, and leave a comment as such.
> m3middle: Make All_floats_legal constant true instead of variable.

- m3-sys/m3middle/src/Target.m3
i.e. starts("SPARC") or "SOL" (SOLgnu, SOLsun historical
sparc32_solaris targets using Sun cc or GNU cc, which
I changed to be just a few lines in config files, not
entire target/config)
> m3middle: Remove unused function IsSPARC.

- m3-sys/m3middle/src/Target.m3
This does not affect m3cc, llvm, or integrated backend.
Though that isn't a bad idea.
> m3middle: For C backend only, make Allow_packed_byte_aligned constant false.

- m3-sys/m3front/src/values/Decl.m3
Along with, I think Allow_packed_byte_aligned,
they threaten to induce gratituitous target-specific layout.
They are not used anywhere in-tree and I am told they are not needed.
This change makes them an error but leaves the rest of the support in,
so it can be restored if needed. In which case I'd still want
them gone when using the C backend.
> m3front: Remove <*LazyAlign*> and <*StrictAlign*>

- m3-sys/m3front/src/builtinInfo/InfoModule.m3
- m3-sys/m3middle/src/Target.i3-old2
- m3-sys/m3middle/src/Target.m3
- www/upgrading.html
Remove ThisPlatform enum from runtime.
Nobody uses it and it is a build and maintenance problem.
The string form remains.
Update out of date documentation a little.
Removing the list of targets from the runtime
relaxes requirements on build order, when adding targets,
but cm3/m3core coupling can still trigger similar situation.
> m3middle: Remove long list of targets.

- m3-sys/m3front/src/builtinInfo/InfoModule.m3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
- m3-sys/m3middle/src/TargetT.i3
m3middle/m3front: Change from Little_endian: boolean to enum Endian {Undefined, Little, Big}.
This is a little more verbose but the point is to have a distinguished value for uninitialized, the popular 0,
so that quake/config can set TARGET_ENDIAN or maybe TARGET_ARCH and not necessarily TARGET,
so the matrix of config file might go away, or at least common code will set Target = BuildDir = arch + os.
This does not really require that, but it might make it clearer if there are multiple sources of same/similar information.
> m3middle/m3front: Change from Little_endian: boolean to enum.

- m3-sys/cminstall/src/config-no-install/NT.common
The problem was that given:
Foo.m3
Foo.i3
We do
cl -c foo.m3.c > foo.lst
cl -c foo.i3.c > foo.lst
In parallel, colliding on foo.lst.
The fix is to instead:
cl -c foo.m3.c > foo.m3.lst (or even foo.m3.c.lst)
cl -c foo.i3.c > foo.i3.lst
We only use the last path element but I believe other parts
of builder require that to work.
The redirection could also be entirely removed. It is just to get more deterministic quieter output.
> Config:Fix and reenable parallel backend for NT.common.

- m3-sys/m3back/src/m3makefile
a clarification of other comment.
It is said there is a hack here and it should be fixed,
but no details are provided as to what is wrong with the code
or what it should do instead.
I wrote the purported hack and it seems and seemed like a reasonable
correct efficient thing. I'm open to alternative judgement and direction but nothing clear was provided.
> m3back/m3makefile: Add comment implicitly requesting

- m3-sys/m3tests/src/m3makefile
- m3-sys/m3tests/src/p2/p269/Main.m3
- m3-sys/m3tests/src/p2/p269/m3makefile
- m3-sys/m3tests/src/p2/p269/m3overrides
fails an assert in integrated backend. p269.
https://github.com/modula3/cm3/issues/58
> int64 tests: Add small excerpt from p240 that

- m3-sys/cm3/src/Builder.m3
The thinking is that oskind is a small number equivalences
like Win32 and Unix, but os is a larger set of similar
but unique things like Solaris, Darwin, Linux, FreeBSD, NT.
In particular, we already are using the enum OSKind for this.
target_os then might come back with this new meaning, or not.
> builder: Rename internal target_os to target_oskind.

- m3-sys/m3middle/src/CoffTime.c
- m3-sys/m3middle/src/CoffTime.i3
- m3-sys/m3middle/src/POSIX/CoffTime.c
- m3-sys/m3middle/src/POSIX/CoffTime.i3
- m3-sys/m3middle/src/POSIX/m3core.h
- m3-sys/m3middle/src/WIN32/CoffTime.i3
- m3-sys/m3middle/src/WIN32/CoffTime.m3
- Add comments that INTEGER should be LONGINT.
- Add comments that C code should not traffic in
traced references (it inhibits transition to precise GC).
- Comment out unused CoffTime.OfFile, which is what prior
comments are about.
> m3middle: Cleanup CoffTime.

- m3-sys/cminstall/src/config-no-install/Unix.common
For the sake of caltech-other/newuoa, when CC fails, try again with -gstabs.
There is no great answer here.
Maybe best is to add fortran_source, upon gfortran or ifort,
and build these from .f instead of .s. Building from .s is pretty bad.
I removed -gstabs+ recently from SYSTEM_CC because it does generate incorrect symbols for recent shipping gcc, which is quite frustrating.
> config: Fallback to -gstabs for caltech-other/newuoa.

- m3-sys/cminstall/src/config-no-install/Unix.common
See commit a7cbbc920531623a10bcddfbe024418b551afa12
Author: Jay Krell <jaykrell@microsoft.com>
Date:   Sat May 12 05:11:18 2018 -0700
Do not disable command echoing, and...
Later consider making it optional but on by default.
It is a little noisy and breaks test automation that wants to verify expected stdout/stderr (and doesn't filter out lines that start SYSTEM_CC)
The logic is remove any number of leading @ not just the first:
C:\s\cm3\m3-sys\m3quake\src\QMachine.m3(1532):        | '@' => echo := FALSE;
(* strip the leading magic characters *)
n := 0;
len := Text.Length (command);
WHILE n < len DO
CASE Text.GetChar (command, n) OF
| '@' => echo := FALSE;
| '-' => ignore_errors := TRUE;
ELSE EXIT;
END;
INC (n);
END;
IF n # 0 THEN
command := Text.Sub (command, n);
END;
So you cannot …
> Unix config: Restore NoEcho on gcc.

- m3-sys/m3back/src/M3C.m3
m3front does like:
set_source_file("../AMD64_DARWINc/WordMod.m3 => ../src/builtinWord/Mod.mg")
That one string with two obvious files, is considered one file.
This damages debugging (this file does not exist) and is unnecessarily
target specific, damaging portable redistribution formats.
For now as an optimization hack we trigger off of:
last char is 'g'
contains " => "
but a more complete slower approach is to replace
build_dir value with literal "build_dir" or such.
Or have a two level build_dir:
../output
../output/amd64_darwin
and then only the first would appear usually, which at least
addresses the portable distribution problem I was
initially handling while still leaving debugging broken.
> Remove build_dir from C output. (i.e. roughly target)

- m3-sys/m3back/src/M3C.m3
m3c: When putting declare_enum_elt in the comments in the C, really, the comments (for debugging)..
output the textual name of the enum elements, not the internal M3ID.
The M3IDs are unfortunately not stable across targets.
That should be investigated.
But the text was the intent here anyway. Also output the integer value (of the enum, not the internal text).
This goes a long way toward converging the C output across targets.
> m3c: Output enum element text not internal ids, in comments.

- m3-sys/cm3/src/Builder.m3
- m3-sys/cm3/src/M3Backend.i3
- m3-sys/cm3/src/M3Backend.m3
- m3-sys/m3middle/src/TargetT.i3
i.e.
replace FROM Target IMPORT M3BackendMode_t
...M3BackendMode_t...
with:
IMPORT Target;
Target.M3BackendMode_t
It is a tradeoff. The verbosity is not necessarily more readable,
and the second part of the name is globally unique.
This is only done a little bit, in code I added and code
I am likely to change soon (separating cosmetic and semantic
changes).
This is purely cosmetic. There is no semantic change.
> cm3,m3middle: Switch to some two level imports.

- m3-sys/cm3/src/Builder.i3
- m3-sys/cm3/src/Builder.m3
- m3-sys/cm3/src/Dirs.m3
- m3-sys/cm3/src/Main.m3
- m3-sys/m3middle/src/Target.i3
This is possibly useful.
Expose through a global in Target, which I really do not love, but is the existing practise.
It breaks multithreaded compilating to multiple targets.
Modules are overrated, objects/records/structs are really the thing to use, for state/variables.
Modules are good for functions and types and constants.
> Compute backend mode earlier.

- m3-sys/cm3/src/M3Build.m3
- m3-sys/m3middle/src/Target.i3
This might enable making output more target-independent.
> Export build_dir to backend via middle.

- m3-sys/m3back/src/M3C.m3
This goes a long way toward converging C output to be the same for many platforms.
It affects debugging, but not much.
The paths were relative anyway, and the relevent source files have just one line, i.e. generic instantiations.
Though more generally, anything can be in output_dir.
But again, we are keeping the file name, so no nbd I think.
Ideally we would have fullpaths, for debugging, but we already don't.
> m3c:Remove ../output_dir/ from the starts of source paths.

- m3-sys/m3back/src/M3C.m3
It was avoiding printing strings that might close a comment but oops.
> m3c:Print the printing of init_chars parameters.

- m3-sys/cm3/src/M3Build.m3
- m3-sys/cm3/src/Main.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
from the backend to the middle end, as it will likely get more calls, from m3front.
Also change how characters are compared, so `'\\' == '/'`.
> m3c:Move the logic to cleanup source paths

- m3-sys/m3front/src/builtinInfo/InfoThisFile.m3
- m3-sys/m3front/src/values/Module.m3
i.e. for Compiler.ThisFile and LinkerInfo.
This another significant move toward having the C backend output be the same across platforms.
> m3c:CleanupSourcePath more.

- m3-sys/cm3/src/Dirs.m3
- m3-sys/cm3/src/Main.m3
cross builds work, i.e. computation of TARGET.
Broken today/yesterday.
> cm3: Restore prior quake evaluation order so that

- m3-sys/m3quake/src/QMachine.m3
print the existing and attemped values.
This might help, a little.
> m3quake:When assigning over a readonly variable and failing,

- m3-sys/cminstall/src/config-no-install/I386_CYGWIN
- m3-sys/cminstall/src/config-no-install/I386_MINGW
- m3-sys/cminstall/src/config-no-install/NT.common
cm3cfg.common already said:
if not defined("BUILD_DIR")
readonly BUILD_DIR = ...
end
But NT, Cygwin, Mingw unconditional:
readonly BUILD_DIR = ...
The result of this is that on non-NT systems you can say:
cm3 -DBUILD_DIR=output
but on NT that gives an error about assigning to a readonly variable.
The underlying code is a bit confusing.
First we do the assignment in code.
I think I put that in.
And we write out quake code to do the assignment,
and before evaluating that we evaluate the config file.
So the sequence is:
BUILD_DIR=output
readonly BUILD_DIR=something else
BUILD_DIR=output error
With this change it should be:
BUILD_DIR=output
skip readonly BUILD_DIR=something else
BUILD_DIR=output no error
Probably it should be possible to say readonly.
> config: Let BUILD_DIR from command line always dominate config files.

- scripts/python/pylib.py
There is this question of appending "C" to BUILD_DIR.
This remains in question.
Previously scripts would try to guess what config would do.
If they disagreed, annoying error.
This made me want to not append C ever.
Yet there is a reason, that is hard to argue away -- the C backend
is not quite ABI compatible with gcc or integrated backends, because
of how static links are passed.
In considering this yet again after a build break, I realized
what should happen is scripts should just tell config what
it wants, rather than trying to coordinate.
> scripts: Make BUILD_DIR agree between config and scripts.

- m3-sys/m3middle/src/Target.m3
This might have regressed recently, i.e. getting naming conventions
while initializing quake. That should be looked into, but
it doesn't matter much. The naming convention stuff is wierd
because I am not sure it keeps host and target straight.
And Windows supports forward slashes.
> m3c: Replace backward slashes with forward in line directives.

- m3-libs/m3core/src/win32/WinBase.i3
Record layout rules recently changed.
This broke the important coincidence between windows.h
and the Modula-3 rewrite of it in .i3 files.
Which perhaps were wrong all along, or skirting the rules.
This causes getting a file's size to be misreported,
as very large, and then memory allocation to hold it to fail.
In particular
FILETIME = RECORD
high, low: UINT32
END;
got 8 byte alignment and then catastrophe putting
that in other records, padding got inserted, offsets
changed, etc.
This goes to show perhaps that rewriting .h files
in .i3 is a bad idea, if you do not have control of those .h files.
If we owned the .h we would only have INTEGER and LONGINT
and nothing ever smaller. And we'd have even number of runs
of INTEGER, so there'd never be any implicit padding for alignment.
And we'd …
> Win32: Add some "BITS FOR".

- m3-sys/cm3/src/Builder.i3
- m3-sys/cm3/src/Builder.m3
- m3-sys/cm3/src/Main.m3
This reverts commit 7508af6f1bec3f293153017914ae103531822234.
It turned out not to be useful, and, unrelated, accidentally
removed Builder.SetupNamingConventions.
On the timing, the thing is, it is set before we create/run
the backend. It is set in config before config does
conditionals. So it is probably set early enough.
> Revert "Compute backend mode earlier."

- m3-libs/m3core/src/runtime/POSIX/m3makefile
This was the only current system using sbrk.
The rest are all historical though it might be nice to try them
and move them to mmap.
> m3core: Switch Linux/amd64 from sbrk to mmap.

- m3-sys/m3back/src/M3C.m3
I'm not sure what happened here -- it was working? It broke?
Certain compilers? But no big deal I guess.
> m3c: In line directives replaces backward slash with forward slash.

- m3-libs/m3core/src/runtime/common/Compiler.tmpl
Nobody in-tree uses it.
The problem with Compiler.ThisPlatform_String is it makes
the C backend output different for every system, for m3core.
It isn't even all that old, no time to build up users.
I replaced Compiler.ThisPlatform with it around 10 years ago.
The problem with Compiler.ThisPlatform was it forced
the matter of not rebuilding m3core with new compiler when
adding a platform. Because the compiler and runtime both
had a big enum with all platforms. The enum is now gone from
both places. I guess nobody was using that either.
If someone really uses this, choices:
- They can compute it ad-hoc but not terrible in ifdef C.
- They can compute it at runtime with uname on Unix.
- They can restore this, but not if using C backend or
if bootstrapping (see how we handle the thread …
> m3core:Remove Compiler.ThisPlatform_String.

- m3-libs/m3core/src/float/m3makefile
NT remains a hold out though current toolsets do support it.
We can probably also write platform specific code for it.
The only Unix hold out was {I386,SPARC32,SPARC64}_SOLARIS
with the comment that it was for Solaris < 2.10.
I did at some point test AMD64_SOLARIS, and Solaris 2.10 is already
quite old, and this holds back all Solaris builds, since
we don't discern precise version, just aimed for low common denominators.
Just m3makefile change.
Various old code remains, should someone really need it.
This will help converge C backend output though I hadn't checked these.
> m3core:Assume C99 for float on all current Unix platforms.

- m3-libs/m3core/src/unix/uin-common/Uin.i3
This should be deleted soon as well.
> m3core: Fix struct_sockaddr_un.sin_family to be sun_family.

- m3-libs/m3core/src/unix/uin-len/Uin.i3
This should go away before long really.
> Add struct_sockaddr to the Darwin/BSD Uin.

- m3-lectern/lecternclient/src/POSIX/LecternClientPosix.m3
- m3-lectern/lecternclient/src/POSIX/LecternServerPosix.m3
- m3-libs/m3core/src/unix/Common/Usocket.c
- m3-libs/m3core/src/unix/Common/Usocket.i3
- m3-libs/m3core/src/unix/uin-common/Uin.i3
- m3-libs/m3core/src/unix/uin-len/Uin.i3
- m3-ui/jvideo/src/POSIX/Jv.m3
Uin-len vs. common is a source of C backend variation
across Unix platforms.
Provide instead:
INTEGER Uin__bind_un(const char*);
INTEGER Uin__connect_un(const char*);
INTEGER Usocket__accept_un(int);
which fill in struct sockaddr_un and call bind or connect or accept.
While there also avoid the silent buffer overflows of the old code.
> m3core: Remove struct_sockaddr_un from .i3 files.

- m3-libs/m3core/src/unix/uin-len/Uin.i3
This reverts commit a9886790444fa05ffad31d857abc2c9aa8ca9ec8.
It wasn't needed as I thought, and now delete both.
> Revert "Add struct_sockaddr to the Darwin/BSD Uin."

- m3-libs/m3core/src/unix/uin-common/Uin.i3
It isn't there for Darwin and BSD.
> Remove Linux struct_sockaddr also.

- m3-libs/m3core/src/unix/uin-common/Uin.i3
They are missing for Darwin/BSD and are not used.
> m3core:Remove struct_sockaddr_in6 and struct_in6_addr.

- m3-comm/udp/src/Common/UDPInternal.i3
- m3-comm/udp/src/Common/UDP_c.c
- m3-comm/udp/src/Common/m3makefile
- m3-comm/udp/src/POSIX/UDPPosix.m3
For portability and C backend convergence
So porting can ignore the len field, and the len vs. no-len does not perturb C backend output.
> udp:Refactor sockaddr_in usage into C.

- m3-comm/udp/src/Common/UDPInternal.i3
- m3-comm/udp/src/POSIX/UDPPosix.m3
drive C backend convergence and portability.
Clarify the calling convention.
> m3-comm:Refactor sockaddr_in usage into C to

- m3-comm/tcp/src/POSIX/TCPExtras.m3
- m3-comm/tcp/src/common/IPInternal.i3
- m3-comm/tcp/src/common/IP_c.c
- m3-comm/tcp/src/common/IP_h.h
It should be removed from the entire tree so that it can be removed from m3core and all the Unix platforms look the same in this regard.
> m3tcp: Ongoing struct_sockaddr removal.

- m3-comm/tcp/src/POSIX/TCP.m3
- m3-comm/tcp/src/POSIX/TCPExtras.m3
- m3-comm/tcp/src/common/IPInternal.i3
- m3-comm/tcp/src/common/IP_c.c
This is so that Unix systems are more similar and C backend output can be identical at least in some places.
> Ongoing sockaddr removal.

- m3-comm/tcp/src/POSIX/TCP.m3
- m3-comm/tcp/src/POSIX/TCPExtras.m3
- m3-comm/tcp/src/common/IPInternal.i3
- m3-comm/tcp/src/common/IP_c.c
- m3-comm/tcp/src/common/IP_h.h
- m3-comm/udp/src/Common/UDP_c.c
- m3-comm/udp/src/POSIX/UDPPosix.m3
The "abstraction" recognized at least to fit legacy code, is protocol specific wrappers.
i.e. IPv4 specific.
i.e.
instead of
WrappingUpSepcificHighLevelFunctions as I was doing or low level bind(generic sockaddr* that must match underlying system), introduce bind_in(ipv4 address and port)
Along with these though, to support existing low level code, we can provide bind(portable/ideal sockaddr
that gets converted, so the older code can be left asis.
Older as in, it does not work with ipv6 w/o some work.
The protocol specific functions should be moved to Usocket.
> m3_comm: Somewhat refactor.

- m3-libs/m3core/src/unix/Common/Usocket.c
Windows does define AF_UNIX but not provide implementation/types, at least not until recently.
And I missed an ifdef.
> Usocket: Fix Windows build after 0584b288f5d083705371da01813d1249f80b27bc

- m3-libs/m3core/src/thread/PTHREAD/m3makefile
Only when using C backend.
The files are internally ifdef'ed so this a build perf tweak otherwise.
> m3c:Compile all Thread*.c files for increased convergence.

- m3-sys/m3back/src/M3C.m3
damaging ability to diff output. So do not output the comment.
This needs further attention.
> m3c:m3front does not always reveal_opaque in the same order,

- m3-sys/m3back/src/M3C.m3
This reverts commit 819bd8b87da764f1dc9f582ceb404e6be3e92f92.
This will be fixed correctly.
> Revert "m3c:m3front does not always reveal_opaque in the same order,"

- m3-sys/cm3/src/Makefile.m3
- m3-sys/cm3/src/Version.c
- m3-sys/cm3/src/m3makefile
- m3-sys/cm3/src/version.quake
m3: Move version from C object to C source, using `__TIME__` and `__DATE__.` This enables diffing
compiler output across multiple runs. Otherwise there is always a difference.
The behavior where cm3 recompiles a little and relinks
every time, is preserved. The offending content is placed
in a comment.
This is a little gross, but comparability of bootstraps is worth something.
> cm3: Move version from C object to C source, using

- m3-sys/cminstall/src/config-no-install/cm3.cfg
i.e. $PROCESSOR_ARCHITECTURE, except translating x86 to I386.
Really this should run cl.exe and detect its target.
> config: On NT host default to native compile, not I386_NT.

- m3-libs/m3core/src/atomic/m3makefile
Current MIPS64/Linux and ARM32/Linux (armhf) seem to support atomics over 1, 2, 4, 8
so remove prohibition against similar but not same:
ARMEL_LINUX, MIPS64_OPENBSD, MIPS64EL_OPENBSD.
PPC and Sparc32 remains as purportedly missing atomic double.
mips32 probably too. Investigate later/never.
It is possible OpenBSD's compiler has less support.
And when ARMEL_LINUX was introduced it was like v5 or v6.
These otherwise are a barrier to portable distribution.
Perhaps we do need a way to tunnel through this conditionality though.
> Extend atomics support on arm32, mips64.

- m3-comm/netobj/src/m3makefile
- m3-comm/netobj/src/netobjrt/StubLib.m3
- m3-sys/cm3/src/Builder.i3
- m3-sys/cm3/src/Builder.m3
- m3-sys/cm3/src/Utils.i3
- m3-sys/cm3/src/Utils.m3
- m3-sys/m3front/src/builtinTypes/WCharr.i3
- m3-sys/m3front/src/builtinTypes/WCharr.m3
- m3-sys/m3front/src/exprs/TextExpr.m3
- m3-sys/m3front/src/misc/M3WString.m3
- m3-sys/m3front/src/misc/Scanner.m3
- m3-sys/m3front/src/values/Module.m3
- m3-sys/m3linker/src/Mx.i3
- m3-sys/m3linker/src/MxIn.m3
- m3-sys/m3linker/src/MxOut.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
- m3-sys/m3quake/src/MxConfig.m3
Unfortunately, widechar is 16 or 32bits, depending
on command line and config. This seem dubious but this
PR does not change it.
The initialization worked by evaluating cm3.cfg a second time,
by virtue of MxConfig.Get(), ignoring the command line.
Evaluating cm3.cfg a second time, while ignoring command line
is a bad idea. It issues ignored errors when you try things like
cm3 -DROOT or -DTARGET.
This PR does have the side effect of cm3 command line working
to set the size, via -DUnicode_WIDECHAR
But the real point is to not evaluate cm3.cfg twice,
in particular, the second evaluation ignores the command line.
Previously widechar initialization was in cm3 and poked locals
in m3linker and m3front.
Original author did not realize that m3middle's role is to be shared
by various. And Target …
> Rework widechar size initialization.

- m3-libs/m3core/src/atomic/m3makefile
Comment out conditional until failures materialize on PPC32, SPARC32.
It is conceivable nobody is or will be running these.
(PPC_DARWIN is now two architectures old and PPC_LINUX, PPC_OPENBSD, SPARC_LINUX
likely had no users except me)
32bit x86 can certainly do do atomic longint and we'll see
also about mips32, arm32, riscv32, hppa32, m68k, etc.
Quite possibly though we'll end up with I386_UNIX, AMD64_UNIX, etc.
where Unix = FreeBSD, OpenBSD, NetBSD, DragonflyBSD, Solaris, Linux,
instead of merely Unix32le, Unix64be, etc.,
depending on future build/scripting machination. We'll see.
> atomic:Write atomic conditional on processor not complete system.

- m3-sys/mklib/src/Main.m3
I saw these tonight with Visual C++ 2008/amd64.
It is an old toolset and I am keen on dropping
support for old toolsets, but maybe only much older,
not this one.
ie.
https://www.microsoft.com/en-us/download/details.aspx?id=44266
More generally we could consider skipping any symbol
with a leading underscore or two.
> mklib: Skip __mask@ symbols.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3middle/src/Target.m3
This suppports I386_NT and hopefully no other platorm
has multiple calling conventions.
And cleanup a little.
> m3c:Fix calling conventions. It was very little code.

- scripts/python/boot2.cmd
- scripts/python/boot2.py
- scripts/python/pylib.py
if python2 not in path, use py.exe
scripts:Pass through -D.
So you can say e.g.
do-pkg.py -DM3_BACKEND_MODE=C I386_NT -DROOT=/s/cm3 m3core buildship commands
do-pkg.py -DM3_BACKEND_MODE=0 I386_NT -DROOT=/s/cm3 m3core buildship commands
etc.
boot2.py Windows: Run python2 or wow that's new \windows\py.exe
So we get all the pylib.py command line handling
and don't need boot2.cmd.
This is all esp. better now that the widechar initialization is fixed.
Environment variables should not be needed and loops are more easily
written on Windows.
Deprecate boot2.cmd like boot2.sh.
Pass C through boot2.py.
boot2.py could use more in terms of command line pass through.
It should probably call functions instead of running command lines, which would have fixed the .exe too.
Granted, still should be using …
> scripts: Fix boot2.py on Windows.

- m3-ui/ui/src/winvbt/WinScrnFont.m3
Add new defaulted unused boolean parameter to lookup.
> Partially fix WinTrestle breaks since XFontConfig changes.

- m3-ui/ui/src/vbt/ScrnColorMap.i3
"..\src\MGPaintOp.m3", line 60: No value specified for record constructor field (2.6.8). (xrgb)
"..\src\MGPaintOp.m3", line 97: No value specified for record constructor field (2.6.8). (xrgb)
2 errors encountered
Just initialize to zero.
We could remove this data on Wintrestle but it does not seem worth it.
> Wintrestle: Fix more recent compilation breaks.

- m3-libs/m3core/src/win32/WinDef.i3
- m3-libs/m3core/src/win32/WinGDI.i3
- m3-libs/m3core/src/win32/m3makefile
- m3-ui/ui/src/winvbt/WinTrestle.m3
"..\src\winvbt\WinTrestle.m3", line 2048: warning: LOOPHOLE: expression's alignment may differ from type's
Expose windows.h:
MAKEPOINTS
GET_X_LPARAM
GET_Y_LPARAM
macros as functions, as well as the implied
inverse PointsToLParam. This fix use that last
one.
Again it would be nice if READONLY and VAR
were guaranteeably pointers. Without such
guarantees we use UNTRACED REF and ADR.
LPARAM is size_t or ptrdiff_t.
POINTS is a struct containing two 16bit integers.
> Wintrestle: Fix new alignment/loophole warnings.

- m3-sys/m3front/src/values/Formal.m3
The C backend insists that all records passed as parameters to functions be of declared types.
Even though pop_struct implies passing a pointer, and the backend could
just pass it as void* or forward declare the struct.
Ideally, eventually, pop_struct passes by value, leaving the ABI details to the backend.
Lately builds fail because m3front is skipping record declarations.
For example:
C:\s\cm3\m3-ui\ui\src\trestle\InstalledVBT.m3
```
PROCEDURE InitChild (j: Join; ch: VBT.T; p: DeleteProc)=
VAR
grandChild := NEW(GrandChild, proc := p);
child      := StableVBT.New(grandChild);
BEGIN
EVAL grandChild.init(ch); (* line 41 *)
j.trueChild := ch;
EVAL j.init(child)
END InitChild;
```
The init call has some default parameters.
It is actually:
C:\s\cm3\m3-ui\ui\src\split\HighlightVBT.i3(31):
``` …
```
> m3front: Restore declaration of record types.

- m3-ui/mgkit/src/GraphVBT.m3
These are probably m3front regressions and undo this when
they are fixed.
> mgkit: Simplify initializer due to recent m3front changes.

- m3-sys/m3front/src/exprs/CallExpr.m3
which line of input the compiler is having trouble with.
> m3front: Before failing assert(false) indicate

- m3-sys/m3back/src/M3C.m3
When faced with constant initialization that are
range violations, m3front issues a warning and continues
to produce IR like:
INT8 a := 266;
M3c wouldd detect this and rightly fail.
But the tests need to compile, eh? p268.
> m3c: Allow invalid IR that m3front produces.

- m3-sys/m3tests/src/p2/p285/Main.m3
- m3-sys/m3tests/src/p2/p285/m3makefile
This used to work but with PackedVars it no longer compiles.
> m3tests: Add small regressed program involving arrays.

- m3-sys/cm3/src/Main.m3
C_COMPILER: meant to be SUN or GNU (i.e. on Solaris targets)
LINKER: MS or GNU (i.e. I386_NT or I386_CYGWIN)
Affects linker switch format.
WINDOWS_LIBRARY: MS (win32) or X
THREAD_LIBRARY: MS (Win32) or pthread
Cygwin was actually configured to use MS but either make sense.
BACKEND_MODE: 0-3, C
HOST_GNU_MAKE: make vs. gmake etc.
The code was never active here and is little known.
The options, which remain a useful and implemented
factoring of config, can be set from command line with -D
or config file or ideally but probably not environment (hopefully with CM3_ prefix).
Defaulting them to host would introduce somewhat undesirable host variation.
Granted, a host variation that might be sticky anyway (i.e.
these correlate strongly with Win32 vs. Posix, a factoring we might
be stuck with …
> cm3: Remove commented out code to default target to host properties:

- m3-sys/cm3/src/version.quake
to be target defaults, but that can be set from config
or command line and are most likely never used from here:
GNUPlatform
CCompiler
Linker
ThreadLibrary
WindowLibrary
GNUMake
BackendMode
TargetNaming
NamingConventions
Using them would cause changes in backend output and is not particularly worthwhile.
If they are really needed, we can feed them into generated C instead of .m3/.i3
so they do not affect backend output, but that still breaks portable redistributable.
Another way to do is configure defaults when you compile cm3, such as autoconf/cmake do.
That can generate .c or .i3/.m3, but just do it later.
We could imagine a two phase build where we build cm3 w/o default, then run this
quake to update cm3 w/ defaults. But I don't think anyone ever really used this code
and we can …
> version.quake: Trim more host properties intended

- m3-libs/m3core/src/thread/PTHREAD/ThreadOpenBSD.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/thread/PTHREAD/m3makefile
and the OpenBSD ThreadPThread__ProcessStopped was failing assertions also.
Use the portable code instead, that unfortunately has
to squat on a signal (global resource with no arbitration),
and send signals (which initially hurt debugging but configuration
fixes that).
We really need cooperative suspend.
I am seeing a free of an invalid pointer sometimes now though.
> m3core:OpenBSD dropped pthread_suspend_np, pthread_resume_np years ago

- m3-sys/cminstall/src/config-no-install/NT.common
- scripts/python/make-dist-multiple-jay.cmd
- scripts/python/make-dist.py
that I added, for the sake of bouncing between C toolsets.
Only for NT (which possibly has the worst compat in this area,
of mixing C toolset versions). It surely worked, but bouncing toolset version is probably
too much hassle to be worth it. The reliable approach that involves
no toolset mixing is to bootstrap from generated C which is
totally viable now (I need to double check NT386, but even so).
If someone again starts the exercise of mixing .objs among toolsets,
or creating packages that interoperate across toolsets, this
could be brought back.
It really is a nice idea to create a Modula-3 NT redistributable
toolset, that is not tied to a specific Visual C++ compiler/linker/runtime,
but it might be too much trouble.
Maybe better off to reduce static linking, which is where these …
> config and scripts: Remove the special support for suppressing symbols,

- m3-sys/cminstall/src/config-no-install/NT.common
This was to support very old C toolsets, like Visual C++ 2.0.
The usual define to check for, that the compiler
automatically includes, is _WIN32 with the leading underscore.
Let's reduce noise a little bit in what command lines we run.
> config: Remove -DWIN32 when compiling C.

- m3-libs/m3core/src/win32/WinBase.i3
This reverts commit e4b03b497b517134f565c02c9d77560cb958f212.
I cannot explain this.
There was a problem and this fix made sense, but was perhaps
overkill. I can no longer reproduce the original problem though, so revert.
> Revert "Win32: Add some "BITS FOR"."

- m3-libs/m3core/src/unix/Common/Uconstants.c
Specifically just have jmpbuf be jmpbuf.
Do not fix Cygwin's size (they are off by a factor of 4) nor arrange for I386_NT / I386_CYGWIN interop.
> m3core: Remove some historical if 0'ed out code.

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
This is possibly needed on other platforms.
> Solaris: Add coroutine stubs so it links.

- m3-sys/cminstall/src/config-no-install/Solaris.common
somewhat like how Sun cc is searched for. Not yet tested but convincing.
> Solaris config: Expand search for g++/clang++ to present locations,

- m3-libs/m3core/src/win32/m3makefile
to avoid clash with Posix socks and breaking Solaris build.
jay@solaris:~/cm3-boot-I386_SOLARISc-d5.11.0-20210326$ make
./c_compiler -g -mt -xldscope=symbolic -xarch=pentium_pro -Kpic -c  WinSock.i3.c
/opt/solarisstudio12.4/bin/CC -g -mt -xldscope=symbolic -xarch=pentium_pro -Kpic -c WinSock.i3.c
"WinSock.i3.c", line 869: Error: Only one of a set of overloaded functions can be extern "C".
Move some Quake functions earlier to accomodate new caller.
> Windows config: Only compile Winsock.i3 on Windows platforms

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
> m3core: Fix coroutines after 7c4beadb04cced6d678274a5fa1703d277dae6c6

- m3-libs/m3core/src/runtime/common/RTProcessC.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
Solaris: pthread_atfork handlers run with signals deferred/disabled,
leading to deadlock between fork and collect.
It may be desirable to have the collector "back off" more,
releasing locks. However instead here "for now" instead
run the fork handlers outside of fork on Solaris where
signals work, so forker will suspend.
The usual suspect better approaches of cooperative suspend and spawn instead of fork + exec are not solutions on their own.
The fork handlers are for anyone in the process that forks without exec.
The scenario of anyone doing that, on Solaris, not going through m3core, remains subject to lock and state corruption.
> Solaris: pthread_atfork handlers run with signals deferred/disable.

- m3-libs/m3core/src/C/Common/Csetjmp.i3
- m3-libs/m3core/src/C/Common/CsetjmpC.c
- m3-libs/m3core/src/runtime/ex_frame/RTExFrame.m3
- m3-libs/m3core/src/unix/Common/Uconstants.c
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/misc/Marker.i3
- m3-sys/m3front/src/misc/Marker.m3
- m3-sys/m3front/src/values/Module.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
This is to fix building Solaris C++.
Use sigsetjmp instead of _setjmp.
This is a nice portable idea.
But, sigsetjmp should be paired with siglongjmp, which is ok, but also sigsetjmp is not portably linkable,
i.e. it fails with Linux/m3cc.
So do it for Solaris only.
Solaris/m3cc not tested, just Solaris/m3c will be.
> Fix Solaris/C++ wrt _setjmp vs. sigsetjmp.

- m3-sys/cminstall/src/config-no-install/Solaris.common
This fixes building e.g. m3-ui/ui.
Mentor is still broken due to arrays.
> Solaris config: Add -lXft -lfontconfig.

- m3-sys/cminstall/src/config-no-install/Solaris.common
- scripts/python/pylib.py
Solaris is four targets with six names:
SPARC32_SOLARIS, SOLgnu, SOLsun
SPARC64_SOLARIS
I386_SOLARIS
AMD64_SOLARIS
> Solaris: Use C backend.

- m3-sys/m3cc/src/gnucc.common
Forgot to add three ends for Quake.
> gnucc.common: Fix after 21d3342e2c550812fcf4cabefc339131b5a7e5c4

- m3-sys/cminstall/src/config-no-install/Solaris.common
-Bstatic does nothing
-dy fails
-G fails; it is -shared for SunCC
This area needs improvement-- we should find what we can find
and then decide the type.
> Solaris config: -G is not for gcc, nor -dy -Bstatic

- m3-sys/cminstall/src/config-no-install/AMD64_SOLARIS
- m3-sys/cminstall/src/config-no-install/Solaris.common
At least one one the others is failing, I suspect 32bit layout is the problem but need to work through each.
> Solaris config: Limit C backend to AMD64_SOLARIS for now.

- m3-libs/m3core/src/runtime/common/RTHeapInfo.m3
Otherwise the function has no return and a Solaris C++ compiler errors (not a warning, an error).
Not the best IR here and LLVM might suffer similarly.
Perhaps should be fixed up in m3front. Perhaps m3c can workaround it, probably.
But hopefully this is ok "for now", maybe forever.
Consider definitely a workaround in m3c.
Note that several other C and C++ compilers do not notice (Sun cc, Microsoft C and C++, GNU C and C++; the reasonable outlier is Sun C++, with many others not tested: IBM xlC, Intel, Clang, Green Hills, etc.)
> Solaris C++:Add return to RTHeapInfo.Producer.

- m3-sys/m3middle/src/Target.m3
This long standing reasonable simple behavior fixes C backend
for multiple targets including I386_NT and SPARC32_SOLARIS.
This matches most 32bit targets, except Linux/x86 and Linux/m68k.
C backend cannot portably reduce alignment without compiler specific pragmas/syntax or debugability loss.
C backend can portably increase alignment.
This likely allows for more atomics.
This does not necessarily align stack, but it aligns globals, heap, and record offsets.
m3cc and llvm retain 32bit alignment here.
Which again, does not match C on many platforms and I recommend restoring them too.
> m3c: Restore 64bit types to 64bit alignment, on 32bit targets.

- m3-sys/m3front/src/exprs/CallExpr.m3
- m3-sys/m3front/src/exprs/Expr.m3
- m3-sys/m3front/src/values/Value.m3
Some backends reject non-valid functions w/o return.
e.g. m3c/Sun C++ and LLVM.
LLVM fixes it itself, m3c/Sun C++ does not yet.
Maybe undo this later when m3c handles it, by adding a return there.
Add internal error messages before assert(false)
> m3front: Add returns to non-void functions.

- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
get removed by some platforms. i.e. fix linking on some targets.
> m3core: Add AtForkPrepareOutsideFork to .i3 so it does not

- m3-sys/cminstall/src/config-no-install/AMD64_SOLARIS
- m3-sys/cminstall/src/config-no-install/I386_SOLARIS
- m3-sys/cminstall/src/config-no-install/SOLgnu
- m3-sys/cminstall/src/config-no-install/SOLsun
- m3-sys/cminstall/src/config-no-install/SPARC32_SOLARIS
- m3-sys/cminstall/src/config-no-install/SPARC64_SOLARIS
- m3-sys/cminstall/src/config-no-install/Solaris.common
SUN or GNU compiler and we'll look for both.
Remove clang++ support as it does not work.
Remove -i from gcc-as-ld invocation as it errors.
-Wl,-i should work but seems to get dropped.
Use -pthread instead of -pthreads for hypothetical clang support.
> Solaris config: Rewrite so that you do not have to specify

- m3-libs/m3core/src/thread/PTHREAD/ThreadFreeBSD.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/thread/PTHREAD/m3makefile
lead to crashes, for some reason. Switch to the gnarlier portable form at least "for now". It works.
Also fix the FreeBSD-specific code to compile, if enabled.
> FreeBSD: The FreeBSD specific suspend/resume and/or stack scan

- m3-libs/m3core/src/unix/Common/Uconstants.c
and we verify that this is greater than all errno values.
FreeBSD/12.2/amd64 has a few errnos in the 9900-9999 range.
Skip those.
The two duplicated users of Uerror.Max do not need an exact number,
and growing their static arrays to 9999 is perhaps overkill.
Granted, that code is never used, really.
Having static arrays is perhaps not needed either.
Having Uerror.Max is perhaps not needed either.
The way the FreeBSD/libc++ code is stated, it could be additional errors, but this should be ok for now.
We should really consider eliminating  Uerror.Max, as a portability burden that provides near zero value.
There are uses in the tree, they are not quite correct or needed.
> FreeBSD m3core: We have const Uerror.Max = 248

- m3-libs/m3core/src/unix/Common/Uconstants.c
Either way is not great, but note that the following code makes it less bad, and perhaps suffices.
i.e. checks for >9900 && <9999
> m3core: Check for _LIBCPP_ERRNO_H instead of cplusplus & clang & FreeBSD.

- scripts/python/pylib.py
It should work and is slightly useful, to quickly get
a system that can cross to NT, but there is some problem
with the Makefile, seen on Solaris and BSD and not super
worth resolving for now. Eventually we should use cmake here (and carry the entire system this way)
> scripts: Remove mklib from Unix bootstraps.

- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
PROCEDURE Target.TypeImage() => CONST Target.TypeNames[]
CONST CG.TypeName[] =>  CONST Target.TypeNamesFixedWidth[]
CONST Target.TypeNames[] => CONST Target.TypeNamesDotted[]
Arguably should be VAR or PROCEDURE but the main
point is they are all Target.TypeNames. Two were
already CONST so stick with that.
Arguably do not need three forms, but the point
is consolidation not behavioral change, and exact
printed strings are behavior.
This is cleanup. Keep the duplication, but put it all near each other.
> m3-sys: Consolidate strings for CG type names.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/misc/CG.m3
m3front m3c: More verbose errors in m3front and m3c tracing (comments).
This is a bit unfortunate, 'cause the tracing is really verbose.
In time we might produce two files, verbose and not-verbose
and compile the not-verbose one. Or save the binary
form and write a dumper, which we really already have both.
There is a problem to be debugged here.
> m3front m3c: More verbose errors in m3front and m3c.

- scripts/python/pylib.py
Yes it solves a problem, but it is too confusing to track when it is appended.
The point is that C backend is not always call-compatible
with gcc backend, specifically because of how the static link
is passed. gcc backend can pass it in an ABI-defined
extra register. C backend passes it as last parameter.
We might be able to put an attribute on it to unify, in gcc/clang.
Maybe declspec(thread) on NT. Gross but quite efficient really.
Maybe some assembly for NT/x86.
But probably nothing ever really.
Eventually, we should have:
/src/m3/libs/m3core/foo.m3
/src/m3/libs/libm3/bar.m3
/obj/m3/libs/m3core/foo.o
/obj/m3/libs/libm3/bar.o
where /obj/m3 is entirely user-specified and can contain arch-os.
i.e. out of tree builds like autotools and cmake
at the multi-package level, not individual …
> scripts: Remove C from end of build_dir.

- m3-sys/cm3/src/Makefile.m3
- m3-sys/cm3/src/version.quake
Like this:
C:\s\cm3.2\m3-sys\cm3>cm3 && AMD64_NT\cm3.exe --version
--- building in AMD64_NT ---
ignoring ..\src\m3overrides
****  PARALLEL BACK-END BUILD, M3_PARALLEL_BACK = 20
Critical Mass Modula-3 version d5.11.0
GitInfo: https://github.com/jaykrell/cm3/commit/fb4448d43a0283855fe362d1206c79726966b19a
https://github.com/jaykrell/cm3/commits/vd
remote:https://github.com/jaykrell/cm3
revision:fb4448d43a0283855fe362d1206c79726966b19a
branch:vd
last updated: 2021-02-24
compiled: 2021-04- 3 13:57:27
configuration: C:\cm3\bin\cm3.cfg
host: AMD64_NT
target: AMD64_NT
Several notes:
- It can be changed.
- If git fails, it prints "unknown", like:
Critical Mass Modula-3 version d5.11.0
GitInfo: unknown
last updated: 2021-02-24
compiled: 2021-04- 3 13:57:27
configuration: C:\cm3\bin\cm3.cfg
host: …
> version:Add git info.

- m3-sys/cminstall/src/config-no-install/NT.common
- m3-sys/cminstall/src/config-no-install/cm3cfg.common
It seems like too much for too little.
And it hides warnings from C++ compiler that I would like to see and maybe deal with.
Hopefully tests can be usefully run without this.
Perhaps by having expected output appear, in order, but
allow extra interspersed lines.
Or perhaps keep all of this, perhaps.btt
As I recall, I wrote all this but nobody cared much either way.
Reduce overall build system code?
> NT config: Remove listing file code.

- m3-sys/cminstall/src/config-no-install/NT.common
This is really probably from the listing file support (https://github.com/modula3/cm3/commit/6b301e6bf50a0b36cca1a7c6432dced46975fbba),
so they'd both go to the listing file.
> NT config: Leave stdout and stderr separate.

- m3-sys/cminstall/src/config-no-install/cm3cfg.common
Like earlier, but I missed this spot.
It serves a useful purpose, but is confusing and eventually
eventually the output directory will just be the current directory,
like for normal cmake/automake out of tree builds.
> config: Do not append c to BUILD_DIR for C backend.

- scripts/python/c_compiler
- scripts/python/pylib.py
i.e. g++, c++, C++
Favor c++ over CC to be case insensitive but Solaris installs only CC in places.
Not all platforms available for test, e.g. VMS and OSF/1.
> scripts: Switch the bootstraps generally to C++ compiler driver.

- m3-sys/cm3/src/Version.c
used `__cdecl` without `#include "m3core.h"`
> version.c: Fix after 5069e5e60ef9f6b2a79074b9dc619c6829a5d49f

- m3-sys/cminstall/src/config-no-install/NT.common
- scripts/python/pylib.py
-Gy is ancient and good. Newer toolsets also have -Gw for unused data.
We really to do this for gcc also.
> NT config/bootstrap: Compile with -Gy so linker can remove unused functions.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/Umman.c
and it fails to compile. It happened to me just now.
> Solaris: Sometimes mmap/mprotect/munmap expect char* not void*

- m3-sys/cm3/src/Main.m3
- m3-sys/m3quake/src/MxConfig.i3
- m3-sys/m3quake/src/MxConfig.m3
- m3-sys/m3quake/src/MxConfigC.c
- m3-sys/m3quake/src/MxConfigC.i3
HOST_WORD_SIZE_TEXT with Fmt.Int() thereof.
There are vanishingly few users (one).
This is arguably a problem, but part of a much larger one.
> MxConfig: Replace HOST_WORD_SIZE with BITSIZE(INTEGER) and

- m3-sys/mklib/src/Main.m3
Next step is to stop writing import libraries here at all.
And try to write the .def file from cm3 instead of mklib.
This addresses warnings seen, since listing file code removed, i.e. duplicate exports of floating point constants, that we should not even export once.
> mklib: Skip exporting what we also skip in .def file.

- m3-sys/cm3/src/Builder.m3
- m3-sys/cm3/src/M3Backend.i3
- m3-sys/cm3/src/M3Backend.m3
- m3-sys/m3back/src/M3C.i3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3cgcat/src/Main.m3
This is an area where mfront/m3cg could use improvement.
Specifically m3cg should be directly given a unique identifier
prefix per source, that must be unique across the static link.
i.e. if appended with a recurring sequence, like empty
or 1, 2, 3, etc.
And/or specifically m3front should be producing these names,
for all backends. No nulls, no stars, no duplicates, no assumed
file level static linkage.
i.e. for segments.
For any backend, append before link should be trivial.
I'm a bit reluctant to mess with m3front though.
While this change does not change m3front, it does tunnel
through package/library/program name, and kinda source name to the backend.
There is also a notion of unit_name, but it does not differentiate
interface from module, which is perhaps unfortunate (I admit,
I …
> m3c: Uniquify segment names by package ("library or program") and module

- m3-sys/m3back/src/M3C.m3
Everything should still work with old gcc, but will likely warn, like for unsigned < 0.
The problem with this code is not merely that it is large or ugly,
but that it is conditional and therefore untested, until/unless such time as there is CI using gcc before 4.3.
Granted, the old gcc lives on because of GPL 2 vs. 3.
If someone sets up CI to get regular testing, we can restore this.
> Remove most or all of the accomodation for gcc prior to gcc 4.3.

- m3-sys/m3back/src/M3C.m3
This is with the goal of concatenating all the files
from a library/package, or across multiple library/packages,
for a crude form of LTCG/LTO, or easier to bootstrap
because cm3 will be just one file.
> m3c: ifndef around struct types.

- m3-sys/m3back/src/M3C.m3
They are template-like macros.
This is in the interest of concatening all the files
of a package or program, so cm3 redist is one source file.
Rename ifndef_type to ifndef.
This defines things to just be themselves.
ifndef foo
define foo foo
void foo(...) { ... }
endif
> m3c: Add ifndef around helper function instantiations.

- m3-sys/cminstall/src/config-no-install/NT.common
I added it. Probably nobody noticed or cares.
It produces warnings, now that I removed the listing file stuff.
It is not a bad idea, but perhaps this is not the way.
Really the output should be factored and formed so that
cm3 does not actually import this unused stuff.
cm3 is not really CreateProcess/LoadLibrary intensive, as it runs per package
not per source, and even this we might reduce.
ws2_32.dll (commented out)
wsock32.dll advapi32.dll gdi32.dll netapi32.dll user32.dll comctl32.dll rpcrt4.dll
iphlpapid.dll (typo)
It also doesn't work on quite old no-longer-untested toolsets (Visual C++ 2003 Express and pre-Visual++5.0sp?)
> NT config: Remove the delayload support.

- m3-sys/m3cggen/src/Main.m3
They do not appear in the binary/file, but are useful (will be shortly).
> m3cggen: Fill in the missing opcodes.

- m3-sys/m3back/src/M3C.m3
This is so files can be concatenated.
ifndef:
Rename "type" to "id". It is not just for types.
Prepend "m3once_". Remove m3_ prepend at call sites.
Add newlines.
> m3c: ifndef around set helpers.

- m3-sys/m3back/src/M3C.m3
Or more generally around the type-independent prefixes.
Add some comments and rename some identifiers for clarity,
e.g. "already_printed" and "types_already_printed".
The goal is to concatenate files and compile with one/fewer
compiler invocations esp. so that cm3 is one redistributable source file.
M3c is not significantly altered for this goal, nor is common
code lifted out to a library. There are tradeoffs to every approach.
> m3c: Ifndef guards around conversion helpers.

- m3-sys/m3front/src/values/Module.m3
before:
ADDRESS Foo_I3(void);
after:
ADDRESS Foo_I3(INTEGER mode);
They were incorrect in .i3 files, correct in .m3 files.
The mismatch leads to errors when you concatenate m3c output, and there is no reason for it.
Move the implementation declaration to common code for reuse by the import.
> m3front: Declare binders correctly.

- m3-sys/m3back/src/M3C.m3
shortn define m3once_foo m3once_foo to define m3once_foo
> m3c: Missed newline in ifndef guard.

- m3-sys/m3back/src/M3C.m3
4715 not all control paths return a value
4716 must return a value
> m3c: Suppress more warnings.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/runtime/common/RTLinkerC.c
This is maybe unfortunate, maybe ok.
m3core.h had:
if defined(__cplusplus) || __STDC__
typedef void* ADDRESS;
else
typedef char* ADDRESS;
endif
but m3c outputs:
(* TODO ideally these are char* for K&R or ideally absent when strong
typing and setjmp work done *)
typedef char* ADDRESS;
typedef char* STRUCT;
and the resulting code adds integers to ADDRESS.
Which is fine for char* but non-standard/illegal for void*.
The strong typing thing might happen eventually, esp. for structs,
but it also requires the offseting to be done by name/index
in m3back instead of m3front layout, so pretty far out.
If you concatenate the m3c output with the hand written C
you get approximately one error, about RTLinker__GetEnvironmen
We could alternatively rename one of them, or just have m3c
output "char*" …
> m3core: Unifity ADDRESS with m3c.

- m3-sys/m3back/src/M3C.m3
when concating m3c output with hand written Win32 C.
> m3c: Replace CHAR with UCHAR due to mild conflict with windows.h

- m3-libs/m3core/src/unix/Common/Umman.c
../src/unix/Common/Umman.c: In function cchar* Umman__mmap(caddr_t, WORD_T, int, int, int, m3_off_t):
../src/m3core.h:315:106: error: invalid conversion from void* to ADDRESS (char*)
Keep the parameters char*, which converts to void*.
But make the return void*, which converts from char*.
> m3core: Fix compiling Umman.c on most systems due to Solaris fix.

- m3-ui/anim3D/src/x-opengl/X_OpenGL_Base.m3
This fixes compiling x-opengl using the C backend.
Generally calling conventions, having more than one, is an anomoly.
It is only for NT/x86.
However when using the C backend, m3middle/m3front/backend deliberately
do not know this.
So for example, I386_NT is the same as ARM32_NT.
So all code needs to be written as if it is targeting NT/x86,
regarding calling conventions.
The fix is trivial and in good style.
Instead of casting to PROCEDURE(), cast to GLu.GLUtessAnyProc.
> x-opengl: Fix calling convention of callbacks.

- m3-libs/m3core/src/thread/m3makefile
Simplifiy selection of Win32 threads. Some of the conditions were redundant.
Require TARGET_OS to be set, such as to NT, CYGWIN, LINUX, DARWIN, etc.
Generally TARGET = TARGET_ARCH + "_" + TARGET_OS.
TARGET_OS is a further refinement of Posix generally (or NT vs. MINGW,
though I think MINGW is really just a toolset, not a host or target).
TARGET_ARCH isn't really interesting at all. Nothing outside of m3cc
is architecture-specific, except for GET_PC and M3_HOST, which are
optional.
The actual factors are WORD_SIZE and TARGET_ENDIAN, which
do closely correlate with TARGET_ARCH, but such decomposition
hypothetically makes for fewer (four) total combinations.
(if you consider sparc, mips, ppc alpha etc. 'cause actually there are only
a few interesting processors these days: amd64, arm64, …
> m3core: Remove FreeBSD 4 special case.

- m3-sys/mklib/src/Main.m3
m3core now provides Win32 types/constants for all systems,
allowing some cross scenarios (the .lib file format
working here should go away, just write .def files, in m3front)
> mklib: Remove m3core duplication.

- m3-libs/m3core/src/C/Common/CsignalC.c
- m3-libs/m3core/src/C/Common/CstdioC.c
- m3-libs/m3core/src/C/Common/CstdlibC.c
- m3-libs/m3core/src/C/Common/CstringC.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/unix/Common/UdirC.c
- m3-libs/m3core/src/unix/Common/Uexec.c
- m3-libs/m3core/src/unix/Common/Umman.c
- m3-libs/m3core/src/unix/Common/UnixC.c
- m3-libs/m3core/src/unix/Common/Uprocess.c
- m3-libs/m3core/src/unix/Common/Upwd.c
- m3-libs/m3core/src/unix/Common/Usignal.c
- m3-libs/m3core/src/unix/Common/Usocket.c
- m3-libs/m3core/src/unix/Common/Uugid.c
- m3-libs/m3core/src/unix/Common/Uuio.c
- m3-libs/m3core/src/unix/Common/Uutmp.c
so that multiple .c files can be concatenated without warning/error
> m3core: undef M3MODULE before defining it,

- m3-libs/m3core/src/thread/Common/ThreadInternal.c
- m3-libs/m3core/src/time/POSIX/TimePosixC.c
This is maybe not best solution -- try to find a shared definition
or unshare the name.
> m3core: undef THOUSAND to support concat

- m3-sys/cm3/src/Utils.i3
- m3-sys/cm3/src/UtilsWin32.m3
- m3-sys/cm3/src/cm3unix.c
- m3-sys/cm3/src/m3makefile
was an automated copy of it.
This is an old bootstrapping hack that inhibits concating files.
> cm3: Use Unix.link instead of local Utils.link that

- m3-libs/m3core/src/unix/Common/UnixLink.c
Call CreateHardLink more directly, requiring Windows 2000 or newer.
> m3core: Require Windows 2000.

- m3-libs/m3core/src/m3core.h
- m3-sys/m3back/src/M3C.m3
so m3c output can be concatented with hand written .c and .h
m3c and m3core.h do not necessarily agree on the exact type of INTEGER
and WORD_T. m3core.h pays to get ptrdiff_t/size_t defined
and uses them, except in VMS corner case.
m3c provides int32 and int64 and lets m3front/m3middle decide.
These should always end up the same size, but could be different
types, like int vs. 32bit long, or long long vs. 64bit long.
> m3c/m3core.h: ifndef guards around INTEGER and WORD_T

- m3-sys/m3back/src/M3C.m3
- Use supplies the identifier, instead of putting m3once on it.
- Remove some unnecessary.
- Converge some symbols m3_foo vs. ifdef m3foo.
More ifndefs are likely coming, in particular because
all the hand written functions are difficult to replicate with
matching signature in Modula-3 CG, as Modula-3 CG does not have
equivalent of C char. So everyone will probably be defined
and import will wrap declarations with ifndef.
> m3c: Tweak the ifndefs.

- m3-sys/m3front/src/types/RefType.m3
This should greatly help let m3c and C prototypes match.
> m3front: When reference types have a user name, pass it to declare_typename.

- m3-sys/m3back/src/M3C.m3
Simpler but perhaps too fragile/ambiguous. We'll see.
> m3c: Tweak how text is turned into valid types.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UtimeC.c
m3_time64_t is always 64bits.
m3_time64_t is always at least the size of time_t.
m3_time_t shall be repurposed to mean time_t or time64_t, whichever
the C system supports. Many 32bit systems started with 32bit time_t
and then later added 64bit time64_t or such. Sometimes both are available
at the same time, sometimes defines silently changes time_t to time64_t,
which is easier to program, if you do not need a mix. From the
looks of it, this is all for OSF/1.
> m3core: Rename m3_time_t to m3_time64_t.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/time/POSIX/DatePosix.i3
- m3-libs/m3core/src/time/POSIX/DatePosix.m3
- m3-libs/m3core/src/time/POSIX/DatePosixC.c
This is ultimately needed for precise GC with cooperative suspend
(unless, something unspecified around finding managed values
in C locals)
This work will be approximately finished when TEXT and MtoC
are removed from m3core.h, since those are the main/only infractions.
> DatePosix: Remove managed types from C.

- m3-sys/llvm/llvm3.6.1/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm5/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/M3x86.m3
- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3front/src/misc/M3.i3
- m3-sys/m3front/src/types/NamedType.i3
- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3middle/src/M3CG.i3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_AssertFalse.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_DoNothing.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
This is so that m3c can generate much higher fidelity
declarations of extern functions.
This is some initial plumbing. More work is needed
to pass and consume the values. A usefully-working
prototype exists.
declare_formal ought to be handled too, but it is unlikely
to matter for the scenario in mind.
> m3-sys/cg/front/back/middle: Add QID to declare_param.

- m3-sys/m3front/src/types/NamedType.m3
initializer at each creation.
Just cosmetically terser and hopefully no less clear.
No semantic change.
> m3front: Rely more on type initializers than explicit

- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/Type.i3
This does bloat non-named types by two integers but this is likely the most elegant solution.
i.e. to get the qid to Formal.EmitDeclaration.
> m3front: Move NamedType.qid to Type.Info.

- m3-sys/m3front/src/values/Tipe.m3
A step towards m3c output being concatenable, with C, and getting same typenames.
> m3front:Include typenames for imported types.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/values/Tipe.m3
e.g.
m3front passes:const_void_star,
m3c produces:m3core_Uuio_const_void_star
to m3front passes:Ctypes__const_void_star
and m3c leaves it alone.
Since types have no linkage, there is danger
of collision. We'll see.
> m3c/m3front: Change typenames from:

- m3-sys/llvm/llvm3.6.1/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm5/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/M3x86.m3
- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_AssertFalse.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_DoNothing.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
This is so things like
INTERFACE Uuio;
`<*external*>PROCEDURE read(...):int`
can return "int" or "Ctypes__int", and not a type with a hash,
so that m3core.h and C backend output can match, and be concatenated,
and then bootstrap is from one large .c file.
This is plumbing toward that goal.
Previously I added the qid (module-qualified id) to the params. This adds it also for the return type.
> m3cg: Add import_procedure(return_type_qid).

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.i3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/values/Procedure.m3
m3front: Pass on result_qid to import_procedure.
m3c: Ditto.
This is a bit of a temporary failure.
The names are coming through with a single item, "int" instead of "Ctypes__int".
But it shows where and almost how to make the right change, once right is decided.
We will maybe want to call GlobalName in m3front like we do for
declare_typename and pass on a TEXT. (usually nil). (err, M3ID, not TEXT).
Not too expensive?
Alternatively, we can change the few we care about on the .i3 side
and have m3c only pay attention to ones with module # 0.
As well we can mechanize "what we care about" as extern-only.
There are likely more options, such as a narrow form of GlobalName,
that returns the module M3ID. Or providing more typedefs
like Uuio__int, etc.
> m3front: Pass on result_qid to import_procedure.

- m3-sys/llvm/llvm9/src/Main.m3
- m3-sys/llvm/llvm9bindings/src/m3makefile
Some LLVM and Windows amd64 related improvements:
1) LLVM9 Add GCharTriple and GCharTriple for AMD64_NT
2) Add AMD64_NT to LLVM_LIB_DIR
3) LLVM9 and AMD64_NT. Edit comment related using nmake
4) LLVM9 and AMD64_NT. Linking with psapi.lib, gdi32.lib, shell32.lib, ole32.lib, oleaut32.lib, uuid.lib, msvcprt.lib, libvcruntime.lib, libcmt.lib, oldnames.lib
5) Add AMD64_NT to LLVM_SOURCE_DIR
6) Add AMD64_NT to LLVM_BUILD_INCLUDE_DIR
> LLVM and Windows amd64 related improvements.

- m3-sys/llvm/llvm9/src/Main.m3
- m3-sys/llvm/llvm9bindings/src/m3makefile
Some LLVM and Windows amd64 related improvements:
LLVM9 Add GCharTriple and GCharTriple for AMD64_NT
Add AMD64_NT to LLVM_LIB_DIR
LLVM9 and AMD64_NT. Edit comment related using nmake
LLVM9 and AMD64_NT. Linking with psapi.lib, gdi32.lib, shell32.lib, ole32.lib, oleaut32.lib, uuid.lib, msvcprt.lib, libvcruntime.lib, libcmt.lib, oldnames.lib
Add AMD64_NT to LLVM_SOURCE_DIR
Add AMD64_NT to LLVM_BUILD_INCLUDE_DIR
Redo of https://github.com/modula3/cm3/pull/407 which I had accidentally not squashed (debatable what to do, and if repair worthwhile, arguments for and against).
> LLVM and Windows amd64 related improvements. #415

- m3-sys/m3front/src/misc/Scope.i3
- m3-sys/m3front/src/misc/Scope.m3
- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/values/Procedure.m3
NamedTypes occur like either:
INTERACE A;
FROM B IMPORT C;
PROCEDURE D():C;
or
INTERACE A;
IMPORT B;
PROCEDURE D():B.C;
In the first case, merely C was being passed.
Now B.C is.
This will help with concatenating all m3c output and hand
written .h/.c. Matching function declarations, without
type hashes, will be trivial, using like:
m3core.h:
ifndef Ctypes__int
define Ctypes__int Ctypes__int
typedef int Ctypes__int
endif
Ctypes__int UnixFoo__Bar(void);
cat m3core.h *.c cm3.c
cc cm3.c
This change is a little invasive, in its changing READONLY
to VAR, but I think it is ok. It can be dialed back somewhat
if there is a problem, or other approaches considered.
Really I think it makes sense to canonicalize/lower
and not just pass through equivalent varying forms.
> m3front: Pass fully qualified ids to backend.

- m3-libs/m3core/src/C/Common/Cstdio.i3
- m3-libs/m3core/src/C/Common/CstdioC.c
- m3-libs/m3core/src/C/Common/m3makefile
- m3-libs/m3core/src/m3core.h
- Use wrapper macros even for returning void.
- m3core.h: Add the higher level wrapper macros for returning void.
(with the token pasting hazard).
We should consider using m3quake + cm3 builtins to write
this stuff out to avoid that hazard thoroughly.
What we have instead is selective based on empirical
findings (i.e. systems with macros like __malloc).
Or remove all the pasting.
- Add comments that Cstdio is unused, untested, but keep it "working".
- Change unsigned to int.
- A few comments here and there.
e.g. todo change m3_socklen_t to int.
> m3core: Mostly cleanup Cstdio a little.

- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/types/Type.i3
- m3-sys/m3front/src/types/Type.m3
- m3-sys/m3front/src/values/Formal.m3
That is, tell backend "INTEGER" and not just int32/int64.
Original attempt was to wrap all types in NamedType.
That still seems reasonable.
But it did not immediately work, I did not debug, and the approach here is to add M3ID name to every Type.info.
This is wasteful but probably ok. Wrapping in NamedType is quite disruptive perhaps.. or should work.
This way we can declare C code as taking/returning INTEGER and have it match m3c output (once m3c processes this data more).
Perhaps at this point we should just change qid=m3idpair to typename=m3id, really.
That is, remove the module: M3ID and have NamedType do a concat and M3ID.Add.
However that has cost, and with most backends, no benefit.
> m3front: Provide a qid to backend for non-named types.

- m3-sys/m3front/src/misc/Scope.m3
commit 41f5de6fd15d5165f0ace7d34ce03ce661ea4eb0
Author: Jay Krell <jay.krell@cornell.edu>
Date:   Thu May 6 12:49:57 2021 -0700
m3front: Cleanup LookUpQID. (#419)
Because I do not really know if it implies a required null check before deference.
> Partially revert:

- m3-libs/m3core/src/C/Common/Ctypes.i3
- m3-libs/m3core/src/win32/WinBaseTypes.i3
This is a non-Modula3-type-system textual trick that should be useful shortly, as part of m3c+*.c concat.
> m3core: Add const_int and const_UINT32 types.

- m3-libs/m3core/src/unix/Common/Ustat.i3
At the Modula-3 level these are equivalent, but this will
help with m3c + *.c concat.
> m3core/Ustat.i3: const char_star to const_char_star.

- m3-sys/m3front/src/values/Tipe.m3
commit 575063b607bed4629111dcd4b3e2254b512796cd
Author: Jay Krell <jay.krell@cornell.edu>
Date:   Fri May 7 20:03:35 2021 -0700
m3front: Provide a qid to backend for non-named types. (#424)
That is, tell backend "INTEGER" and not just int32/int64.
When I tested that, I probably had a mix of attempts
and it worked, but then I undid parts.
The commented out line here seems correct but caused problems.
> m3front: Missed part of naming types:

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
Pass along declare_procedure(return_type_qid) in multipass.
Some shorthands.
Comments in m3cgrd/wr that it is not handled, since the relevant
backends do not use it and will not for long forseeable future.
> m3back: Add printing of declare_procedure(return_type_qid)

- m3-sys/m3front/src/values/Formal.m3
> m3front: Formal: Simplify calls to type compilation.

- m3-sys/m3front/src/values/Formal.i3
- m3-sys/m3front/src/values/Formal.m3
This is "opinionated".
The old fashion of uninitialized data to optimize
away unnecessary initialization I think is long since not the way to go.
> m3front: Formal: Provide and use more initialized types, typically zeroed.

- m3-sys/llvm/llvm3.6.1/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm5/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/M3x86.m3
- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.i3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/types/Type.i3
- m3-sys/m3front/src/types/Type.m3
- m3-sys/m3front/src/values/Formal.m3
- m3-sys/m3front/src/values/Procedure.m3
- m3-sys/m3front/src/values/Tipe.m3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_AssertFalse.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_DoNothing.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
Mostly my very recent introductions.
Some preexisting.
Retain type QID and constant NoQID.
Type.Name existed (uid to text) so rename
Type.QID to Type.Typename (yuck).
If there was an agreed upon format (e.g. Module__Name),
and needed by more backends, QID here could be M3.ID, but
no preexisting backend uses these, and M3C will soon.
> m3-sys: Rename many qid to typename.

- m3-sys/m3front/src/values/Formal.i3
- m3-sys/m3front/src/values/Formal.m3
first non-nil value of type, and then is not
reduced/replaced upon calls to .Check/.CheckInfo.
i.e. it retains NamedType.
Return original_type in Formal.Info.type, so that
splitting and reforming a Formal, as is done, retains the NamedType.
This will lead to duplicate work to reduce the same
types multiple times but that should be ok, not terrible,
and ultimately required.
> m3front: Formal: Add original_type that takes the

- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/values/Procedure.m3
and not just imported procedures.
> m3front: Pass typename for return value of declared

- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/Type.i3
- m3-sys/m3front/src/types/Type.m3
- m3-sys/m3front/src/values/Tipe.m3
splitting it so all types single element names but
only NamedTypes have module.name. A little wasteful but should be ok.
> Move entire name:QID to Type instead of

- m3-sys/m3front/src/values/Variable.m3
i.e. the value before Check lowers it
i.e. it remains NamedType (if it is NamedType)
and Typename "works" (not a hash).
Starting using it for parameters, though put off
handling indirect parameters briefly.
We should probably introduce TypedValue.T
as a common base of Formal.T and Variable.T, or push
more functionality up to the base Value.T.
> m3front: Variable: Add notion of original_type.

- m3-sys/llvm/llvm3.6.1/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm5/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C-save1.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/M3x86.m3
- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_AssertFalse.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_DoNothing.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
This might not be needed but it is the right thing.
In particular, this is for function pointer types only,
and if any of those occur where it matters, they can be
replaced entirely instead via their pieces at low implementation
cost, i.e. via the toplevel. We'll see.
Add printing of declare_formal's typename in M3C.
It is never currently passed from m3front.
> m3-sys: Add typename to declare_formal.

- m3-sys/llvm/llvm3.6.1/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm5/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm9/src/M3CG_LLVM.m3
- m3-sys/m3back/src/M3C-save1.m3
- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/M3x86.m3
- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_AssertFalse.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_DoNothing.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
Again like declare_formal this might not be important and might not get filled in, but it is the right thing.
> m3-sys: Add result_typename to declare_proctype.

- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/values/Formal.m3
- m3-sys/m3front/src/values/Variable.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
That is, given patterns like:
procedure init:
t.type := x
...
procedure 1:
t.type := Type.Check (t.type)
foo (t.type)
procedure 2: (* likely run after procedure 1 *)
EVAL t.type
Change to:
procedure init: (* unchanged *)
t.type := x
...
procedure 1:
VAR type := Type.Check (t.type)
IF Target.LowerTypes THEN
t.type := type;
END;
foo (type) (* maybe *)
procedure 2: (* likely run after procedure 1 *)
EVAL t.type
And then LowerTypes defaults to TRUE, same behavior
as before, but is FALSE when targeting C.
This is expected to help preserve typenames down the line,
without changing the IR (or only a little).
If you survey for Type.Check you will find that I skipped most of them.
This is probably ok or mostly ok, we will see.
This notably breaks pointer comparisons of types, which I have seen a …
> m3-sys: Make lowering of types optional.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/time/POSIX/DatePosixC.c
- m3-libs/m3core/src/unix/Common/Umman.i3
- m3-libs/m3core/src/unix/Common/Unix.i3
- m3-libs/m3core/src/win32/WinReg.m3
m3c output and hand written C, so that they can all be concatented.
Specifically patterns like m3core.h:
ifndef Cstddef__size_t
define Cstddef__size_t Cstddef__size_t
typedef size_t Cstddef__size_t
endif
m3c will then say:
ifndef Cstddef__size_t
define Cstddef__size_t Cstddef__size_t
typedef something-maybe-not-exactly-size_t Cstddef__size_t
endif
They will be concatented, m3core.h will come first.
And then use types like Ctypes_const_char_star
instead of const char*.
Some char* vs. void*.
Some TODO comments.
> m3core: Changes in anticipation of type matching between

- m3-libs/m3core/src/runtime/common/RTIO.i3
- m3-libs/m3core/src/runtime/common/RTIO.m3
Prior, callers had to be unsafe and loophole to address and call PutAddr.
> m3core: Add RTIO.PutRef(REFANY).

- scripts/python/boot2min.py
This is like boot2 but doesn't build all the packages.
It only builds from nothing, up to cm3.
So a nice workflow is:
boot1
untar + make + put cm3 in path + boot2min
instead of boot2, if you just want a working cm3+m3core+libm3
and not the much larger set of libraries and programs
that is the entire system.
> scripts: Add boot2min.py.

- m3-sys/m3back/src/M3C.m3
so ADDRESS can be void* instead of char*.
> m3c: Use char* instead of ADDRESS for pointer math,

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3back/src/m3makefile
This will likely change a lot, to be instead typeid + declare_typename
support, but it is also probably close to correct, and cleans
things up, because same code is needed in a few places, i.e. parameters
and return types and hopefully globals, locals and even temporaries).
Specifically this steers m3c away from the low level
types (int32, int64, addr, etc.) and even typeids
as strings (T1234, etc.), more toward the notion
that types have arbitrary text to representing them ("int", "Foo_T", "Foo_T*",
etc.); which, granted, was already somewhat the case. This change
tries to use qid to form the text when they are provided but
possibly they will go away, and instead more declare_typename use.
Add some comments.
Introduce the ifndefs around typedefs, so that m3core.h can replace them.
Add a …
> m3c: Initial qid support.

- m3-sys/m3back/src/M3C.m3
instead of storing it in Type_t.
> m3c: Move type_text_tail to be a parameter to Type_Init

- m3-sys/m3back/src/M3C.m3
to one mapping of type hash to name.
Types now have text and base_text.
They are initialized to be the same, the same as before, typically to have a hash `T1234...`.
When a typename comes along, text but not base_text is replaced by it.
base_text is used for struct definitions. Other uses of text remain.
This seems to work very well, when there is just one name per type.
It breaks down on the likes of:
TYPE int = INTEGER;
long = INTEGER;
PROCEDURE F1():int;
PROCEDURE F2():long;
but it might suffice. We only want the high fidelity, for C interop, esp. in the code contributing to cm3, so we can concatenate a bunch and have one file for all of cm3.
If real contextual typename presevation is needed, then the prior direction of passing QID along with almost any typeid seems unavoidable.
As …
> m3c: Rework typenames so they work very well, if there is a one

- m3-sys/m3front/src/exprs/QualifyExpr.m3
- m3-sys/m3front/src/values/Formal.m3
NamedType, obj_offset, obj_align, prefixAlign
> m3front: Fix some unused warnings.

- m3-sys/m3middle/src/M3CG_MultiPass.m3
Actual bug, sort of (in work in progress, nobody broken by it).
> m3middle: Fix unused warning return_typeid.

- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/values/Formal.m3
- m3-sys/m3front/src/values/Variable.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
I don't think this is really needed, "just" an optimization, and loses possibly useful information.
> m3-sys: Remove some type lowering for all systems.

- m3-sys/m3front/src/types/Type.m3
In Type.IsEqual and Type.IsSubtype, call StripPacked unconditionally.
> m3front: Remove manual partial inlining.

- m3-sys/m3front/src/types/Type.m3
This is redundant with all callers so should not change anything.
The point being to generally explicitly allow unlowered types,
i.e. named typed (there are other unlowered forms like
packed and subrange, but my concern is named).
> m3front: Strip in Type.AddCell.

- m3-sys/m3front/src/types/OpenArrayType.m3
This is to reduce manual inlining, i.e. an anti-pattern except for maybe perf.
> m3front: Call StripPacked unconditionally in OpenArrayType.Reduce.

- m3-sys/m3front/src/types/ArrayType.m3
- m3-sys/m3front/src/types/OpenArrayType.m3
> m3front: More type-based zeroing initializers.

- m3-sys/m3front/src/types/Type.m3
commit b89d8fe4bab0bfbb8f64799127f3b0fab5863880
m3front: Remove manual partial inlining. (#484)
In IsEqual and IsSubtype, call StripPacked unconditionally.
There were two unintended changes there:
- In IsEqual, call Strip, not StripPacked.
- In IsSubtype, look at info.class after Strip, then call StripPacked.
Symptom of the problem:
C:\s\cm3\m3-comm\serial>rd /q/s AMD64_NT & cm3
Fatal Error: bad version stamps: SerialPort.m3
version stamp mismatch: WeakRef.FromRef
<c1ff6b0d2489bc38> => SerialPort.m3
<28bbb0fb20661e30> => WeakRef.i3
version stamp mismatch: WeakRef.T
<da5baaeae3faad3a> => SerialPort.m3
<74fc644f36110a26> => WeakRef.i3
SerialPort.m3: missing imported type: _t2a11fb7d
SerialPort.m3: missing imported type: _tfb5d45cd
SerialPort.m3: missing imported type: _t98a5b108 …
> mfront: Type.{IsEqual,IsSubtype} Fix my mistake in:

- m3-sys/m3back/src/M3C.m3
Type text formation is confusing and churning enough.
> m3c: Remove some commented out code.

- m3-sys/m3back/src/M3C.m3
So that m3c output can be concatenated.
This affects segments that m3front provides no name for.
Segment names for interfaces and modules were not discernable.
The old names were like cm3_Arg + counter.
The new names are like Arg_m + counter and Arg_i + counter.
m for module, i for interface.
cm3 being library/program.
> m3c: Make unique names more unique.

- m3-sys/m3front/src/types/ProcType.m3
then return typename:NoQID instead of typename:Record.
> m3front: If Record F() is lowered to void F(Record*)

- m3-sys/m3back/src/M3C.m3
Instead of where it was copied from, declare_param.
> m3c: Fix error in procedure TypeText to say TypeText.

- m3-sys/m3front/src/types/Type.m3
in Type.{Strip,StripPacked,Base}.
If there is a cycle, then advancing one at a time
and two at a time will eventually make them equal.
> m3front: Add comment explaining cycle detection

- m3-sys/m3front/src/types/NamedType.m3
Otherwise was likely throwing out the resolved module
yielding "T" instead of "Module__T".
> m3front: NamedType: preserve name around Check but not Resolve.

- m3-sys/m3front/src/types/ProcType.m3
> m3front: Get proc result QID after resolution, so module usually not 0.

- m3-sys/m3front/src/types/Type.m3
Presumably IsEqual, SubType => Error => True is to reduce error cascades.
> m3front: Add comments to Type.m3.

- m3-sys/m3front/src/types/Type.m3
A microoptimization, avoids repeated evaluation of u.info.class, with no loss in clarity. Sort the cases.
> m3front: Type: Change if/elseif chains to case.

- scripts/pkginfo.txt
Adding line:
mysql database
to file pkginfo.txt
Tested by Alexey Ershov ( thanks!) on OS Linux Mint 20.
> Add mysql to pkginfo.txt 

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/misc/Scope.m3
So we get like Ctypes__int instead of INTEGER.
But disable for nested scopes, which do not produce good data currently.
m3front should be using more like GlobalName instead of ModuleName.
This much improves the C output.
> m3c: Enable QID for types.

- m3-sys/m3back/src/M3C.m3
> m3c: declare_typename is inferior to and conflicts with passing typename from each site.

- m3-libs/m3core/src/C/Common/CsignalC.c
- m3-libs/m3core/src/m3core.h
When they are seen together -- the typedefs in m3core.h shall come first and win.
> m3core: Make Csignal__signal prototype agree between Modula-3 and C.

- m3-libs/m3core/src/m3core.h
This helps prototypes match and be correct, when m3c output and hand written C are combined.
> m3core: Change void_star and const from char* to void*.

- m3-libs/m3core/src/C/Common/Cstring.i3
- m3-libs/m3core/src/C/Common/CstringC.c
They have const problems, and are trouble to get correct (C and C++ disagree), and are not used.
Null terminated strings rarely occur in Modula-3, good.
If they are needed they can be put back here or where needed, or outside of cm3 itself (outside of m3core, libm3, sysutils), and likely const ignored.
> m3core: Remove wrappers for memchr, strchr, strrchr, strpbrk, strstr.

- m3-sys/m3front/src/values/Formal.i3
- m3-sys/m3front/src/values/Formal.m3
- m3-sys/m3front/src/values/Variable.m3
They have been replaced by selectively not lowering type.
To retain NamedType.
This approach might not scale though. There are many other places
in m3front where original types are lost, relying
on backends to aggressively cast to a generic pointer type,
and to have structs that are just arrays of bytes.
> m3front: Remove my recent addition of original_type and OriginalTypeOf.

- m3-libs/m3core/src/C/Common/Csetjmp.i3
- m3-libs/m3core/src/C/Common/CsetjmpC.c
It has been replaced with m3_longjmp.
> m3core: Remove no longer used ulongjmp.

- m3-libs/m3core/src/C/Common/Csetjmp.i3
- m3-libs/m3core/src/m3core.h
when m3c output and hand written .c combined.
> m3core: Arrange for Csetjmp__longjmp prototype to match

- m3-libs/m3core/src/m3core.h
There are some confusions around Word.T.
- Is it Word__T or WORD_T? Both exist.
- Is it INTEGER or INT64 or an unsigned type (UINT64 or size_t). Both kinda.
- Does Word.Divide etc. deal in INTEGER or Word__T? Both appear in imports.
This is a mess.
WORD_T was likely my accidental introduction. It should be Word__T.
However Modula-3's lack of full range unsigned types likely contributed to it.
I made WORD_T full range unsigned.
The varying imports of Word.Divide I suspect stem from Word being both
builtin into m3front and there being Word.ig files to parse.
It could also be lack of the new typename feature against the builtins.
And this shows up as errors if you combine m3c and C.
The builtins should probably use the typename Word__T and then m3c and m3core.h can decide what that is.
For …
> m3core: m3c/c convergence.

- m3-libs/m3core/src/C/Common/M3toC.i3
- m3-libs/m3core/src/C/Common/M3toC.m3
Const is missing in a number of places here.
This shows up when you combine m3c output with m3core.h, in which I made similar fixes.
> m3core:M3toC: const fixes

- m3-sys/m3front/src/values/Formal.m3
This is for example, so DatePosix__FromTime is declared in a way for m3c and C to agree.
> m3front: Handle typename on VAR/READONLY parameters.

- m3-libs/m3core/src/m3core.h
- m3-sys/m3back/src/M3C.m3
m3front issues:
declare_typename INTEGER size_t  very questionable
declare_typename INTEGER ssize_t ok
To cope with this, maybe more than necessary:
- m3core.h: provide the various unsigned, unsigned_long, unsigned_int, etc. types.
When combined with m3c output and m3core.h comes first,
this will lock them in as unsigned as they probably should be.
It is in their names, right?
This is only needed in as much as these types occur in
prototypes in hand written C, so this is probably overkill,
which is why I said "and then some".
- m3c: In declare_typename, stop replacing types
with typenames; so for example INT64 will not change to size_t.
Typenames remain for parameters, for which the aggressive
typename work was initially intended, but not on types,
where I was probably being too clever, …
> m3c / m3core: Repair integer types.

- m3-sys/m3back/src/M3C.m3
sys/stat.h. Replace it with another.
> m3c: st_mtime is a macro on Unix and cannot be used along with include

- m3-libs/m3core/src/float/Common/DragonT.i3
- m3-libs/m3core/src/float/IEEE/LongFloat.m3
- m3-libs/m3core/src/float/IEEE/RealFloat.m3
- m3-libs/m3core/src/float/VAX/LongFloat.m3
- m3-libs/m3core/src/float/VAX/RealFloat.m3
> m3core: DragonT.strtod was declared incorrectly.

- m3-sys/m3back/src/M3C.m3
prior to consuming formals and return typenames.
> m3c: Cosmetic whitespace and naming in proctype handling

- m3-sys/m3back/src/M3C.m3
There are several problems to fix.
- We are issuing typedefs for typenames before the base type
is defined or forward declared.
- Fixing that is at first easy, you hook Typename_t into
the existing framework, where types are defined or forward
declared as possible, until done.
- However you then run into that m3front omits many typenames.
- And possibly the hash collisions.
> m3c: Disable typenames again.

- m3-sys/m3front/src/types/RefType.m3
This is a little gross.
Most code does not care about the order.
typenames are not much of a thing.
The C backend however sees a bunch of typenames.
Including that it will synthesize many missing typenames,
like for parameters (or fix m3front?).
Faced with so many typenames, the dilema becomes, what
to use for a typeid in the absence of a nearby typename.
The first name for most types is or shall be merely
a string form of the hash. This suffices for most purposes,
but is ugly, and does not suffice for quite all purposes.
What will likely be the case, is the first non-hash form
will stick. Specifically, the first typename for an indirect or pointer
will be whatever is the underlying's current name, followed by a "*".
Therefore it behooves us to try to give a nice typename before an …
> m3front: RefType: declare_typename before declare_pointer.

- m3-sys/m3back/src/M3C.m3
It was getting replaced with m3_CARDINAL in an upcoming change and breaking stuff.
Putting it in the list here was confusing user code with m3c.
CARDINAL will not occur in user code, because it is reserved in Modula-3.
This is a list of reserved C and m3c identifiers, not a list of Modula-3 identifiers.
> m3c: Remove CARDINAL as a special symbol.

- m3-libs/m3core/src/unix/Common/Usocket.i3
= UNTRACED REF struct_sockaddr_in
This is "needed" for m3c/C matching, though it is more about
a mechanism for const-correctness than about resolving the tremendous
differences between Usocket.i3 declarations and Usocket.c reality, which
will also be fixed.
> m3core: Usocket: Introduce and use {const_}struct_sockaddr_in_star

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UtimeC.c
This is to aid in m3c/C convergence.
This is a confusing area -- too many ideas to name.
Some systems just have time_t. It traditionally
was 32bits, but is these days 64bits.
Some systems to retain compatibility and widen
have a 32bit time_t and a 64bit time_t by some name,
such as time64_t. Tru64 for example has time64_t.
If the underlying system has an explicit 64bit time,
we use that in C. And we call it m3_time_t.
Otherwise, if there is no special 64bit time,
we use "normal" time_t (hopefully 64bits), and call it m3_time_t also.
In Modula3 we have just Utime.time_t and it is always
64 bits, and we convert back and forth through direct
integer assignment/truncation/widening to m3_time_t.
On some systems, maybe there is lossage, but there are
likely no such systems under active …
> m3core: Introduce Utime__time_t = m3_time64_t (=INT64=longlong).

- m3-libs/m3core/src/runtime/common/RTIO.i3
- m3-libs/m3core/src/runtime/common/RTIO.m3
These do violate comments nearby, and are commented as such,
in that they allocate, TEXTs.
But I didn't see that mainstream safe Fmt supports Refs
and I don't want to loophole just for that.
> m3core:RTIO: Add FmtAddr, FmtHex, FmtRef.

- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3front/src/types/NamedType.m3
- m3-sys/m3front/src/types/ProcType.m3
- m3-sys/m3front/src/types/RefType.m3
- m3-sys/m3front/src/types/Type.m3
- m3-sys/m3front/src/values/Formal.m3
- m3-sys/m3front/src/values/Variable.m3
In a few modules Foo.m3, introduce:
VAR debug := FALSE;
.
.
.
BEGIN
debug := RTParams.Present ("m3front-debug-foo");
END Foo.
so that later:
IF debug THEN
RTIO...
END
So then cm3 @M3m3front-debug-foo will enable printing.
Even if/when m3c debugging is better, data intensive programs
benefit from "logging".
> m3front: Debug scaffolding.

- m3-sys/m3front/src/misc/CG.i3
- m3-sys/m3front/src/misc/CG.m3
- m3-sys/m3front/src/values/Variable.m3
- m3-sys/m3middle/src/M3CG.m3
- m3-sys/m3middle/src/M3CG_BinRd.m3
- m3-sys/m3middle/src/M3CG_BinWr.m3
- m3-sys/m3middle/src/M3CG_MultiPass.i3
- m3-sys/m3middle/src/M3CG_MultiPass.m3
- m3-sys/m3middle/src/M3CG_Rd.m3
- m3-sys/m3middle/src/M3CG_Wr.m3
This is needed so const_int and const_UINT32 are not lowered,
and then m3c and C agree.
The point is to preserve const, to keep the "variables" in
read only memory, which is more efficient -- is unlikely
to suffer copy on write (unless it is mprotected), and
will remain backed by original executable not pagefile,
and can remain in CPU cached shared instead of exclusive.
Later better typing may also be possible.
> m3-sys: Plumb typename through import_global.

- m3-libs/m3core/src/m3core.h
There are so many, you start to see why int or INTEGER have broad appeal.
> m3core: Fill in various Utypes gid_t, uid_t, etc.

- m3-libs/m3core/src/unix/Common/Usocket.c
ssize_t is cosmetic (except on VMS) and int is
for m3c/C convergence.
> m3core: Socket: Change INTEGER to int or ssize_t.

- m3-libs/m3core/src/thread/POSIX/ThreadPosixC.c
do not inline and do use alloca to get stack pointer
instead of the address of a local. Either should suffice.
The prior code could fail under optimization.
Caller inlined into callee, leads to intermingling of locals
and no ordering. Such inlining is possible with LTCG/LTO.
There are other places that use address of local.
But Modula-3 lacks noinline and alloca.
Arguably it is ok, as long as some uses are correct.
i.e. at least one of each caller/callee pair that attempt
math on their respective locals.
Also cooperative GC should remove most/all notion of stack,
some day.
> User threads: When attempting to measure stack,

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
e.g. Mac/arm64
Move define outside of ifdef.
> coroutine: Fix build on non-Linux/amd64 Unix.

- m3-sys/m3front/src/values/Variable.m3
This is needed so C globals can be const.
Previously the code avoided this, with an unclear comment. Why?
> m3front: Pass typeids for import_global.

- m3-sys/m3back/src/M3C.m3
Or the globals with the command line variables.
> m3c: Allow enabling verbosity in source.

- m3-sys/m3back/src/M3C.m3
LONGCARD was the only duplicate, self-inflicted.
> m3c: Make duplicate types an error.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/Usocket.c
This is done in the smallest way possible, but maybe not the best.
The files really do not agree.
.i3 says the C takes a pointer to "in" internet v4 socket address.
The functions actually take a pointer to a union, which could be "in",
or "un", or "in6" or maybe others.
Probably we should have per-socket-address-type functions and have Modula-3
multiplex.
Some nearby const fixes.
And sockopt char* vs. void* for the sake of Windows.
> m3core: Make Usocket.i3 and Usocket.c agree. At least for compilation.

- m3-libs/m3core/src/m3core.h
gethostbyname
gethostbyaddr
getgrent
getgrgid
getgrnam
(struct hostent and struct group_t)
> m3core: Fix more Unix prototypes to m3c output and hand written C agree.

- m3-sys/m3front/src/values/Variable.m3
The identifiers do get changed and link fails otherwise.
Broken in https://github.com/modula3/cm3/commit/49ce5350b6e7c135b7cba2da7871d1b4c984ce7e
> m3front: Restore globals to have uid=0 when not targeting C.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/Uprocess.i3
Return m3_pid_t = INTEGER instead of int.
> m3core: Fix getpid prototype to agree between m3c and C.

- m3-libs/m3core/src/unix/Common/Uexec.i3
To match C so that m3c and C agree.
> m3core: Fix Uexec__WNOHANG to have const on Modula-3 side.

- m3-sys/m3back/src/M3C.m3
Give people more time to update.
> m3c: Temporarily remove dependency on updated m3core (RTIO.FmtRef).

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/Unix.i3
- m3-libs/m3core/src/unix/Common/Unix.m3
- m3-libs/m3core/src/unix/Common/UnixC.c
- m3-libs/m3core/src/unix/Common/UnixC.i3
- m3-libs/m3core/src/unix/Common/m3makefile
Fixed sized array is not exactly pointer to element.
We cannot declare and pass fixed sized arrays to C
because other fixed sized arrays passed indirectly will clash.
Typenames should be able to help here but do not presently.
> m3core: Fix pipe prototype to match between m3c and C.

- m3-libs/m3core/src/unix/Common/Unix.i3
fails, at least if the C headers are included.
Use int here, and hope all platforms are ok with that.
Consider widening pid_t. Note that we never use vfork but the wrapper
is left for users outside of tree.
> m3core: Fix vfork prototype. pid_t must match else C compiler

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UnixC.c
ADDRESS is not currently the same as void*. Use ADDRESS. Hopefully fix it later.
This is so m3c output and hand written C agree and can be combined.
> m3core: Fix Unix__ioctl prototype.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UdirC.c
Return struct dirent* instead of void*.
So they can be combined into one file.
> m3core: Fix Udir__readdir to match between m3c output and C.

- m3-sys/m3back/src/M3C.m3
So just make all procTypes untyped (ADDRESS, consider void*).
> m3c: procType hashes omit the return type and are very collision prone.

- m3-comm/tcp/src/WIN32/IP.m3
- m3-comm/tcp/src/common/IPInternal.i3
- m3-comm/tcp/src/common/IP_c.c
- m3-libs/m3core/src/m3core.h
Now that function pointers (ProcType) are untyped (char*),
because they are very prone to type hash collisions,
because they do not hash their return type (besides that the hashing is overall weak),
we can no longer declare Process__RegisterExitor in C
and agree with m3c output.
As a reasonable workaround, return TRUE from IPInternal.Init (C)
and have Modula-3 then Process.RegisterExitor.
The Win32-specific exitor is then added to Unix, but the body
is internally ifdefed, so the function exists but does nothing,
and will never be called.
Another workaround would be to pick the Exitor type for all function pointers, as long as C only needs one accurate function pointer type.
Another workaround is likely to add a typename to Process.i3 for the exiter parameter, instead of an inline type …
> m3core, tcp: Remove Process_Exitor from C surface area.

- m3-libs/m3core/src/C/Common/Cstdlib.i3
- m3-libs/m3core/src/C/Common/CstdlibC.c
This is another case where function pointer hash collisions
cause Cstdlib.atexit declaration to fail to compile.
Again we could fix with:
typename
loophole
having this be the one function pointer type
improve the hashing
This is not used in the tree. Remove it.
If this a problem, we can try the others.
> m3core: Remove Cstdlib.atexit.

- m3-comm/tcp/src/WIN32/IP.m3
- m3-comm/tcp/src/common/IP_h.h
IPInternal__Init now returns BOOLEAN.
IMPORT Process on Win32.
> m3tcp: Fix build or warnings.

- m3-sys/m3quake/src/MxConfigC.c
> m3quake: MxConfigC__HOST returns const char* not char*.

- m3-libs/m3core/src/runtime/common/RTIOc.c
Local-seeming macros are kinda anathema to the idea of concatenating
all the files (so is file-level static, granted).
Bind the Win32 comment closer to the related code.
Make the Win32 file non-empty to avoid warning.
> m3core: Cleanup RTIOc.c

- m3-libs/libm3/src/os/POSIX/OSConfigPosix.m3
- m3-libs/libm3/src/os/POSIX/OSConfigPosixC.i3
- m3-libs/m3core/src/C/Common/CsetjmpC.c
- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/runtime/POSIX/RTOSc.c
- m3-libs/m3core/src/runtime/common/RTIOc.c
- m3-libs/m3core/src/runtime/common/RTLinker.i3
- m3-libs/m3core/src/runtime/common/RTLinkerC.c
- m3-libs/m3core/src/runtime/ex_frame/RTStackC.c
- m3-sys/m3back/src/M3C.m3
- OSConfigPosixC.InitFromC: add const
- RTStack: Redirect record Frame to C type in the new now usual way.
(To avoid C code using type hashes.)
Change unsigned long to ADDRESS to match Modula-3. The fields are not used.
Their type does not matter. Not even the size of the struct matters.
- RTIOc.c: replace INT64 and UINT64 with correct LONGINT,
which is the type in RTIO.i3. Cast LONGINT to UINT64.
- m3c: Try a little hack where all function types
are void (*)(void) instead of the recent previous ADDRESS (char* or void*)
Every case seen so far is actually this. This does not scale,
but there is also only so much C code likely be subjected to this. We will see.
Fixing the hashes is also desirable. More typenames. Or generating
reasonable typenames. Or something.
- RTLinkerC: Usual typename …
> Ongoing m3c/C convergence.

- m3-sys/m3front/src/types/RefType.m3
This reverts commit 3fc7c4de10cd25f8ce3f3a911a9c645b829d6907.
This change was ok, but did not fully meet its goals.
The problem with having declare_typename replace the prior hashed typename,
is that we have things like:
Ctypes:
TYPE int = ...;
TYPE const_int = int;
And then some modules use int, some const_int, some maybe both in either order.
Considering just modules that only use one of them, sometimes the type
replacement is int, sometimes const_int. This is an inconsistency
that leads to errors when concatenting m3c output and C.
A more successful approach is to plumb typenames through more in context.
The missing one then is declare_pointer(target_typename) here.
> Revert "m3front: RefType: declare_typename before declare_pointer. (#549)"

- m3-libs/libm3/src/os/POSIX/OSConfigPosixC.i3
Prior fix failed because the type got renamed to the local module.
> libm3: Really fix const in OSConfig.

- m3-sys/m3front/src/types/RefType.m3
This greatly helps concatenating m3c output with hand written C,
because the typename is then replacable in m3core.h and
can omit hashes, so hand written C need not use hashes.
> m3front: Add target_typename to RefType's declare_pointer.

- m3-sys/m3back/src/M3C.m3
It causes problems, when concatening m3c output with hand
written C, because the names/meaning of the replacements
vary, for example, between int and const_int.
(Modula-3 lacks const in type system, alas).
> m3c: No longer replace types.

- m3-libs/m3core/src/thread/Common/ThreadInternal.c
- m3-libs/m3core/src/time/POSIX/TimePosixC.c
In future will use longer identifiers.
> m3core: Undef before define thousand, million, billion.

- m3-libs/m3core/src/m3core.h
There are warning about inconsistencies.
It is another platform-specificity that is maybe not worthwhile. Maybe.
We should be more worried about the visiblity of all the Modula-3 functions
than the relatively few hand written C functions?
(Besides, nobody ever asked for this optimization.)
> m3core: Disable the specifying of visibility.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/thread/Common/ThreadInternal.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-sys/m3back/src/M3C.m3
For m3c/C convergence.
- Give pthread_create start_routine a typename.
- Inhibit AddressType_t re-typedef.
- Various typename replacements (cond, mutex, pthread).
- Make the global mutex/cond const (they are actually constant pointers to non-constant data,
to hide the sizes from Modula-3)
- various char* vs. void* vs. ADDRESS
- return BOOLEAN from functions that only abort() to unify with other versions
- When measuring stack, do not inline and do use alloca.
Either should suffice.
Without either, inlining can make it not work.
> m3core: Fix pthread types.

- m3-libs/m3core/src/Csupport/big-endian/dtoa.c
- m3-libs/m3core/src/Csupport/little-endian/dtoa.c
Undef Bias after use.
Fix CConvert__Acquire/Release prototype.
Add __cdecl (Windows/x86-ism, otherwise nop)
> m3core: dtoa fixes for C/m3c combination.

- m3-libs/m3core/src/Csupport/Common/dtoa.h
- m3-libs/m3core/src/Csupport/big-endian/dtoa.c
- m3-libs/m3core/src/Csupport/little-endian/dtoa.c
- Move what is repeated in the dtoa.c files into dtoa.h.
- This should almost enable:
cat m3core.h *.c dtoa.h > cm3.c
except for the pesky include. Think about it more later.
> m3core: Consolidate dtoa.

- m3-libs/m3core/src/m3core.h
define M3_HOST for ARM32_LINUX.
> m3core: Add ARM64_LINUX support.

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
> Coroutine: Fix non-Linux/amd64 when combining m3c and C.

- m3-libs/m3core/src/thread/PTHREAD/ThreadApple.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
char* vs. void* (ADDRESS)
int vs. BOOLEAN
void vs. int return in functions that only assert(false)
> m3core: Fix Apple-specific minor m3c/C divergences.

- m3-libs/m3core/src/unix/Common/Unix.i3
The declaration is incorrect for Solaris (sometimes int, sometimes long)
and causes build to fail, and the documentation is severely caveat laden,
and we don't use it.
Anyone using it can/should move a layer further into C and call vfork from C.
Or use fork instead. They are almost the same.
> m3core: Remove vfork.

- m3-libs/m3core/src/Csupport/hand.c
The wrappers are just prefixed with "m3_".
Currently m3c declares and calls the C runtime functions directly.
This has been ok, and is a nice optimization, but a. it is extra
code in m3c b. it causes problems on Mac/arm64 (Mac/all?) when compiling as C++,
and I've always known it was dodgy, to declare these functions ourselves.
> m3core: Add memcmp/memset/memmove/memcpy wrappers, for m3c to generate calls to.

- m3-sys/m3back/src/M3C.m3
Because it is a macro on Solaris and that breaks things.
> m3c: Consider s_addr a reserved word.

- m3-sys/m3back/src/M3C.m3
Prior was cast to taking "() in C or "(...)" in C++.
That is, take anything.
( () in C++ means take nothing, (...) in C is not valid.)
This worked everywhere, except on Mac/arm64/C++, where it crashes.
Mac/arm64/C++ does not allow mixing "..." with strongly declared functions.
C++ works on all other platforms tried, a lot, and C works on Mac/arm64.
But specifically Mac/arm64/C++ did not work.
"more accurately" in that, now use cgtypes, not typeid or type.
This is still weakly typed but much better than before.
The weak proctype hashes continue to be in the way.
We also already use cgtype for the return.
Make call more expression based and less text based, as part of this,
since expressions -- each parameter -- can carry type information.
Reduce/remove used of CGType.Void. CGType.Addr is …
> m3c: When calling indirect, cast the the function pointer much more accurately.

- m3-libs/m3core/src/win32/WinGDIc.c
WinGDIc.c(27) : error C2440: 'initializing' : cannot convert from 'const POINTS' to 'SHORT'
> m3core: Fix error with older Windows compoiler:

- m3-libs/m3core/src/C/Common/Cstdlib.i3
- m3-libs/m3core/src/C/Common/CstdlibC.c
This reverts commit c2d08417eace9a4fb5412f3ff16123a5574deeeb.
m3c now considers all function pointers to be void (*)(void), which lets a few through ok, such as this.
> m3core: Solaris: RTProcess__RegisterForkHandlers: Error: Only one of a set of overloaded functions can be extern "C".

- m3-comm/tcp/src/WIN32/IP.m3
- m3-comm/tcp/src/common/IPInternal.i3
- m3-comm/tcp/src/common/IP_c.c
- m3-comm/tcp/src/common/IP_h.h
- m3-libs/m3core/src/m3core.h
This reverts commit 02f82bb1cdc02116dfbe27506816556868711d28.
Revert "m3core, tcp: Remove Process_Exitor from C surface area. (#600)"
This reverts commit 508f044a320d40b3bf76eda789fbe6042ea31ddc.
These were ok, but now that m3c assumes all procedure types are void (*)(void)
they are not needed. Procedure types frequently have hash collisions.
I had worked around by making them all merely ADDRESS (char* or void*).
However if we assume they are void (*)(void) then we can at least be correct
in this place and another.
> Revert "m3tcp: Fix build or warnings. (#603)"

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/thread/WIN32/ThreadWin32C.c
- m3-libs/m3core/src/win32/WinBase.i3
- m3-sys/m3back/src/M3C.m3
m3c: Define CRT no deprecate to 1 instead of unstated
m3core.h: Start matching windows.h; suppress declspec(dllimport) which is not needed
on functions and cm3 never considers it to be used.
Const fixes similarly.
There is more of this to do and we will have to do something about mklib.
> m3c, m3core: Start fixing single file cm3 for Windows.

- m3-libs/m3core/src/runtime/common/RTHeapInfo.m3
This reverts commit d0ff3b281b30559a57127922d3c10ccad16f4aa4.
m3c now adds returns to non-void functions that lack any.
> Revert "Solaris C++:Add return to RTHeapInfo.Producer. (#269)"

- m3-libs/m3core/src/Csupport/dtoa.c
warning C4711: function 'Bfree' selected for automatic inline expansion
When compiling with /wall /O2
> m3core: Squash warning 4711

- m3-sys/m3quake/src/MxConfigC.c
In particular it demands & instead of && on const int.
This is absurd. Widespread correct readable idioms are disallowed by the new compiler.
> m3quake: Remove some const that clang errors about.

- m3-sys/m3back/src/M3C.m3
Locals_{begin,end}_procedure just call internal_{begin,end}_procedure.
There are no other callers to internal_{begin,end}_procedure.
Combine them.
> m3c: Combine some functions.

- m3-libs/m3core/src/Csupport/dtoa.c
This reverts commit 9f96f0a5dde0e1b0b931e61e860754ac0f145c36.
> Revert "m3core: dtoa: remove code that is not used due to ifdef (#671)"

- m3-sys/m3front/src/values/Tipe.m3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
Type vs. Type.Module vs. Type__Module, to each backend, its own.
This adds flexibility/compatibilty upon commit c847fcd6e22f7b8b674d107350b62ea3fa09b78a.
> m3-sys: Conditionally restore m3cc typenames.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/values/Tipe.m3
- m3-sys/m3middle/src/M3CG_Ops.i3
- m3-sys/m3middle/src/Target.i3
- m3-sys/m3middle/src/Target.m3
They turn out to be, not so useful.
What ended up required is passing type names
to e.g. declare_param, import_global,
so that typenames could precisely match hand written C,
on a case by case basis. Instead of having so many
names for INTEGER and not knowing which to use,
e.g. size_t and ptrdiff_t are the same thing in IR
(Modula-3 has no unsigned types), or int vs. const_int
(Modula-3 has no const). Those are not the entire problem
though.
Perhaps perhaps we could leverage these typenames
kinda like m3cc and get the data through m3gdb, easily,
via the C compiler and Dwarf. Perhaps.
So the code remains, but disabled, and sharing code with contextual typenames, so nothing really extra that is unused.
> m3c: Remove support for context-free typenames.

- m3-sys/m3linker/src/MxGen.m3
to loop over const array.
This is smaller and easier to larger share with m3c.
> m3linker: Move bunch of repeated code over data

- caltech-parser/cit_util/src/UtimeOpsC.c
Esp. for compiling Windows C as C++, for strcpy prototype.
> caltech-parser: Add missing include string.h.

- caltech-other/bool/src/bool.c
- caltech-other/bool/src/bool.h
On Windows 64bit, `unsigned long` is 32 bits, not 64.
Shifting `1UL` by 63 is undefined.
Replace `1UL` with `((bool_var_t)1)`.
Printf bugs are left unfixed.
> caltech-other: Win64: Fix overshifting of integers.

- m3-libs/m3core/src/Csupport/dtoa.c
- m3-libs/m3core/src/Csupport/old_divmod.c
- m3-libs/m3core/src/Csupport/test_hand.c
- m3-mail/llscan/src/err.c
- m3-mail/llscan/src/file.c
- m3-mail/llscan/src/llscan.c
- m3-mail/llscan/src/strlib.c
- m3-tools/gnuemacs/src/flex-bison/lex.yy.c
- m3-tools/gnuemacs/src/flex-bison/y.tab.c
- m3-tools/gnuemacs/src/lex-yacc-HPPA/lex.yy.c
- m3-tools/gnuemacs/src/lex-yacc-HPPA/y.tab.c
- m3-tools/gnuemacs/src/lex-yacc/lex.yy.c
- m3-tools/gnuemacs/src/lex-yacc/y.tab.c
- m3-tools/pp/src/Parse.yacc
- m3-tools/pp/src/flex-bison/y.tab.c
- m3-tools/pp/src/lex-yacc-HPPA/lex.yy.c
- m3-tools/pp/src/lex-yacc-HPPA/y.tab.c
- m3-tools/pp/src/lex-yacc/lex.yy.c
- m3-tools/pp/src/lex-yacc/y.tab.c
- m3-tools/pp/src/lex_help.h
- m3-ui/juno-2/juno-machine/src/OLD/CRowOp.c
Newer C/C++ deprecates/disallows it.
It has a vestigial meaning of "not allowed to take address"
which does in fact help optimization, but otherwise,
compilers do their own register allocation.
> Remove "register" from C.

- m3-libs/m3core/src/win32/WinConstants.c
such as with msys2. Some of the supposed ints are not ints.
> m3core: Fix for WINVER >= 0x0500

- m3-libs/m3core/src/C/Common/CstdioC.c
I got an error that __popen / __pclose not known.
We reference _popen / _pclose though, wierd.
Expand out the macro, seems to fix it.
We do not even use any of this code -- the entire file.
> mingw: Possibly fix popen/pclose problem.

- m3-sys/cminstall/src/config-no-install/AMD64_MINGW
- m3-sys/windowsResources/src/winRes.tmpl
- scripts/python/pylib.py
This is mostly monolithic, but small.
Use the C backend yet again.
Single file release does not yet work for Win32.
> Add AMD64_MINGW config and script support.

- scripts/python/pylib.py
Though strictly speaking I386_CYGWIN and I386_MINGW
have worked with the m3cc backend, and this change
does not change that.
Do not copy .o/.obj/.mo/.io into C backend bootstraps.
Change some starts with to contains (riscv, solaris).
> scripts: Consider Cygwin, Mingw to be C backend only.

- m3-sys/m3quake/src/M3Path.m3
Forward slashes work almost but not quite everywhere on Windows.
Maybe this will help MinGW.
We cannot use forward slashes everywhere though, as that broke something.
> quake: Use forward slashes more.

- m3-sys/m3back/src/M3C.m3
- m3-sys/m3front/src/misc/CG.m3
I am assuming "exported" here means directly callable,
and does not include address-taken and passed outside.
> m3-sys: Assert that nested functions are not exported.

- m3-libs/m3core/src/win32/m3makefile
only provided for 32bit; make the interface also limited the same.
This is a "temporary" hack, but has lived long (since 2013).
The point of this is so we can export what is declared.
So we do not declare stuff that does not exist.
> m3core: WinTabCon and WinListView implementation are

- m3-libs/m3core/src/unix/Common/Uin.i3
- m3-libs/m3core/src/unix/Common/Usocket.c
In particular in6_addr has 8-alignment.
Move unsigned int to before it, and add another for explicit padding for alignment.
Otherwise OSF/1 fails static assert here.
> m3core: Layout out IPv6 for OSF/1 compatibility.

- m3-libs/m3core/src/float/m3makefile
OSF/1 C99 math support is incomplete.
We should be able to provide most/all of it on top of nonstandard names.
See:
read_rnd, write_rnd (and compiler flags)
ieee_get_fp_control
> m3core: Remove C99 math support for OSF/1.

- m3-sys/m3back/src/M3C.m3
This in particular fails with native cc on OSF/1.
> m3c: Avoid duplicate typedefs of REAL, LONGREAL, EXTENDED.

- m3-libs/m3core/src/m3core.h
- m3-sys/m3back/src/M3C.m3
This fixes OSF/1 which defines __DECC.
> m3core/m3c: If _LONGLONG is defined, use long long and LL/ULL.

- m3-sys/m3back/src/M3C.m3
gcc on OSF/1 in particular errors wrt WIDECHAR.
Though g++ and native cc and cxx were ok.
> m3c: Skip some duplicate typedefs.

- m3-sys/m3quake/src/M3Path.i3
Hopefully this doesn't break anything, forward slashes
do usually work on Windows, except sometimes the paths
of things to run, with cmd.
> MinGW: More forward slashes.

- m3-libs/m3core/src/unix/POSIX/m3makefile
commit 2381fac1ad8e409cc727a4cb091cb754c6cda02a
m3core: Fork Unix.i3 for WIN32 vs. POSIX. (#709)
> m3core: Add m3makefile, missed in:

- m3-sys/cminstall/src/config-no-install/ALPHA_OSF
honors naming convention, which we probably have too
many of as well. Else ar commnds fail.
> config: AlphaOsf: Pass -o object to C compiler so it

- m3-libs/m3core/src/m3core.h
- m3-sys/m3quake/src/MxConfigC.c
It is hard to see where the "1" comes from.
It is probably from calling uname() in MxConfigC.c.
Granted, uname does come so close, maybe we should let it
be the decider, thereby getting platform names automatically.
Or rather output directory names and no platforms per se,
just Posixish.
> m3core: Default host to ALPHA_OSF, not ALPHA_OSF1.

- m3-sys/cminstall/src/config-no-install/AMD64_MINGW
Allow use boot2min.py and boot2.py with target boot2.py
> AMD64_MINGW m3_link fix by calling subst_chars()

- m3-libs/m3core/src/m3core.h
- m3-sys/m3back/src/M3C.m3
Hypothetical alloca for OpenVMS was breaking it. Disable that "for now".
It was already working for gcc.
> OSF1: Fix alloca for Tru64/OSF1 with native cc.

- m3-sys/cminstall/src/config-no-install/ALPHA_OSF
- scripts/python/pylib.py
This is config and scripts.
The gcc backend did work a long time ago, and very recently also.
All of native cc, native cxx, gcc (3.4.6? 4.7?) and g++ should all work.
With native cxx, our install is slightly broken and linking requires -oldcxx,
just because one copy of one of the startup files is missing.
From a frontend point of view, old is likely Digital-authored
and "new" is EDG.
Fix path of C compiler in bootstrap.
> OSF1: Switch Tru64 / OSF1 to C backend "only".

- m3-sys/cminstall/src/config-no-install/ALPHA_OSF
This is not to drop OSF 4 support per se,
but the logic looks wrong and I suspect moot.
That is:
- I don't think OSF has the bad default ELF interposability
inefficient semantics.
- It does have something, but I think not as bad.
- I don't think this syntax is related.
- Even if it does, so many other people survive with it,
we probably can do.
And OSF4 vs. 5 was only about controlling that.
I don't remember if I tested on OSF 4 but lately I am using OSF 5.
> config: Remove OSF 4 vs. 5 SYSTEM_CC configuration.

- m3-sys/cminstall/src/config-no-install/ALPHA_OSF
- scripts/python/pylib.py
Use /usr/bin/cxx -x cxx should work.
Link with -oldcxx because of an install problem.
> config: OSF: Switch to C++.

- scripts/python/pylib.py
This reverts commit 42a53c5514ae5492048496123536b7df584b0762.
This will be built upon shortly.
The only reason was seemingly cosmetic, but now the
opposite has a purpose.
> Revert "Bootstrap: Remove the -o and -Fo./ flags as we are"

- scripts/python/pylib.py
It has no long long, or no int64, or something. Probably neither.
Workaround by having .o as dependency.
This depends on -o being restored.
And add the equivalent -Fo to the other NT platforms.
Add -o for OSF and Solaris.
This begs the question of portability to older compilers.
Really we should use autoconf and check sizef(long) == 8.
long long is not really needed on most 64bit targets.
Or maybe we should just require C99/stdint.h and be done
with a lot of cruft. We can still link with -oldcxx.
> scripts: Linking with -oldcxx breaks compiling Main on OSF.

- m3-sys/cminstall/src/config-no-install/ALPHA_OSF
C backend produces these:
codeunreachable: statement is unreachable
badansialias1: This statement uses the type to reference a storage location.
badansialias2: This statement uses the type to reference the same storage location.
fprldonot: IEEE dynamic rounding mode is not supported for long doubles on this platform
labelnotreach: code can never be executed at label
missingreturn: missing return statement at end of non-void function
underflow: underflow occurs in evaluating this expression
Ideally we would work toward producing code that does not produce
any of these warnings, but it can be a fair amount of work,
for later/never.
Regarding underflow, we should generate IEEE754 bytes, not floats.
Including both endian and runtime selection.
Regarding rounding: We do not even use long …
> config: OSF: Suppress a few warnings.

- scripts/python/pylib.py
This makes the code Python2 and Python3 and have the same meaning.
Previously it would run under Python3 but have much
different meaning and fail early.
> scripts: More Python3 compatibility.

- scripts/python/pylib.py
Add ".cpp" support to GetObjectName(a, obj) from pylib.py
> Minor fixes in pylib.py GetObjectName(a, obj)

- m3-sys/cminstall/src/config-no-install/AMD64_DARWIN
Defines SYSTEM_LIBS{"X11"} for MacOS/Intel platforms.  This is not
required for basic functionality, but only so that the full build can
generate the UI libraries.
> add X11 library config for AMD64_DARWIN

- m3-sys/cminstall/src/config-no-install/Darwin.common
This is to allow executables built using cm3 to find and use cm3
shared libraries.  rpath is now the preferred mechanism for locating
shared libraries on MacOS, but it is not 100% compatible with rpath on
other UN*Xes (b/c native ld does not support $ORIGIN, apparently), so
support is added to Darwin.common.
> add rpath support for Darwin platforms

- caltech-other/voronoi/src/geometry.c
- caltech-other/voronoi/src/heap.c
- caltech-other/voronoi/src/mod3_main.c
- caltech-other/voronoi/src/output.c
Removed unused variables and converted gratuitous bitwise operators to
boolean operators.  #justclangthings
Note that this depends on my other MacOS patches to build correctly.
> patch voronoi library to build on macos

- m3-sys/llvm/llvm13/src/M3CG_LLVM.m3
- m3-sys/llvm/llvm13bindings/src/M3DebugInfo.i3
- m3-sys/llvm/llvm13bindings/src/M3DebugInfo.m3
- m3-sys/llvm/llvm13bindings/src/M3DebugInfoRaw.i3
Fix:
= =
Creating library llvm13bindings.lib and object llvm13bindings.exp
M3DebugInfo.mo : error LNK2019: unresolved external symbol LLVMDIBuilderCreateSetType referenced in function M3DebugInfo__CreateSetType
M3DebugInfo.mo : error LNK2019: unresolved external symbol LLVMDIBuilderGetSubrangeConst referenced in function M3DebugInfo__GetSubrangeConst
M3DebugInfo.mo : error LNK2019: unresolved external symbol LLVMDIBuilderGetSubrangeExpr referenced in function M3DebugInfo__GetSubrangeExpr
M3DebugInfo.mo : error LNK2019: unresolved external symbol LLVMDIBuilderCreateDynamicArrayType referenced in function M3DebugInfo__CreateDynamicArrayType
M3DebugInfo.mo : error LNK2019: unresolved external symbol LLVMReplaceArrays referenced in function M3DebugInfo__LLVMReplaceArrays
llvm13bindings.dll : …
> LLVM13: Fix M3DebugInfo__GetSubrangeExpr ( draft mode style)

- m3-sys/m3tests/src/p2/p265/stderr.build
Fix this:
= = =
--- ../src/p2/p265/stderr.build
+++ ../src/p2/p265/AMD64_LINUX/stderr.build
@@ -1 +0,0 @@
-m3front failed compiling: ../Main.m3
= = =
> p265: fix stderr.build

- .gitignore
- m3-sys/cminstall/src/config-no-install/AMD64_FREEBSD
- m3-sys/cminstall/src/config-no-install/AMD64_OPENBSD
- vagrant/freebsd13/Vagrantfile
- vagrant/freebsd13/check-release.sh
- vagrant/netbsd9.1/Vagrantfile
- vagrant/netbsd9.1/check-release.sh
- vagrant/openbsd7/Vagrantfile
- vagrant/openbsd7/check-release.sh
These commits together build and test cm3 on FreeBSD and NetBSD, attempting to compensate for the lack of BSD CI/CD.
> Vagrant boxes for the BSDs

- m3-sys/m3front/src/exprs/ArrayExpr.m3
- m3-sys/m3front/src/exprs/RecordExpr.m3
- m3-sys/m3front/src/values/Method.m3
- m3-sys/m3front/src/values/Module.i3
- m3-sys/m3front/src/values/Module.m3
- m3-sys/m3front/src/values/Procedure.m3
- m3-sys/m3tests/src/e0/e009/stdout.build
- m3-sys/m3tests/src/m3makefile
- m3-sys/m3tests/src/p2/p291/Main.m3
- m3-sys/m3tests/src/p2/p291/TInttt.i3
- m3-sys/m3tests/src/p2/p291/TInttt.m3
- m3-sys/m3tests/src/p2/p291/m3makefile
- m3-sys/m3tests/src/p2/p291/stderr.pgm
These patches (from @RodneyBates) fix bugs with cross-unit access to constants that were revealed as a consequence of the earlier work on array constructors.  The cross-unit bugs did not show up in the test suite, and mainly manifest as crashes in the integrated backend and various Trestle programs, but these all appear to be fixed in my testing.
> constant folding of record expressions

- m3-sys/cminstall/src/config-no-install/Solaris.common
- scripts/python/pylib.py
And therefore bootstrap via gcc backend.
In the scripts I use, not the new ones.
> Scripts: Reduce/remove support for bootstrap via assembly.

- scripts/python/pylib.py
It is only used for specifying C compiler, on never-finished platforms(arm_darwin, alpha_vms),
that can/should be specified another way, i.e. autoconf target or config.guess
or path search or CC or CXX environment variables, or worst case, editing the bootstrap
Makefile, i.e. toward more portable legacy (pre-cmake) bootstraps.
> Scripts: Remove GnuPlatformPrefix.

- scripts/python/pylib.py
This is an old unused disabled function. The idea was
while porting, certain files were "likely" to be edited
and include them in the bootstrap.
It has long since been disabled.
The number of files edited in porting is now very much reduced.
They can be copied with scp, ssh, rsync, editing on target,
or git fetch, etc.
Granted, Git can be difficult to acquire, the copying
can be repitive and is nice to merge with copying of the bootstrap
archive, on-target editing can be difficult, and I have never used rsync.
It was useful to me in the distant past.
I tend to rerun ssh/scp after each edit.
It also was not properly parameterized.
> scripts: Remove UpdateSource functionality.

- scripts/python/pylib.py
This was never finished.
The idea was to build without make, which is easy enough, but not
important.
> Scripts: Remove make.sh functionality.

- scripts/python/make-dist.py
- scripts/python/upgrade.py
It does not work with python3 and appears from comments
not well motivated. Comments indicate an ability
to upgrade from NT386 to I386_NT or NT386 to I386_CYGWIN
or vice versa. This is better done with a rebootstrap these days,
which is not necessarily better or faster, but
is less hacky and must work anyway, vs. this little hack
for rare scenario.
> Scripts: Remove reload.

- scripts/python/pylib.py
Cygwin should still work but user is expected to set environment/path.
> scripts: Remove Cygwin special cases.

- scripts/python/make-dist.py
- scripts/python/pylib.py
The scripts had the notion that cm3 might
be Cygwin or not, and Python might be Cygwin or not,
and convert paths to the form expected by the reciever,
supporting all combinations through a general approach.
Possibly even catering to gcc, wix, and other tools.
The new approach is:
- cm3 and python should be the same "type"
Maybe not everything works, like building MSIs for
or in Cygwin environment.
- Cygwin is not very interesting.
- If there are problems we can restore this code or try something else
- No one minor variant of a minor project is likely worth that much code.
Likely nobody has used this except me, and that was over 10 years
ago.
Some nearby Interix removal.
Possibly breaking the invocation of link.exe by cm3 from Cygwin environment. (Cygwin has a completely unrelated …
> scripts: Remove various Cygwin special cases.

- docs/help/bib.html
I figure linking to archive.org is safe, since they tend to be pretty aware of copyright issues.
> add bibliography link to SPwM3 on the internet archive

- scripts/python/ax_pthread.m4
- scripts/python/boot1autotools.py
- scripts/python/pylib.py
This adds boot1autotools.py.
Presently this just builds cm3, static.
No libs. No install. Not the entire system.
Same as prior boot1.py.
Presently you have to ensure endian and word size match, like the cmake
bootstrap.
In time we should be able to improve all those factors.
In this initial version, cflags are over specified, at configure-time,
like the prior boot1.py does at bootstrap construction time.
Note that for bootstrap construction it makes more sense, as it can
match word size to bootstrap (i.e. on multiarch systems like x86/amd64,
sparc32/spar64, darwin).
Also in time the configure.ac here should be a separate file,
output by cm3 for each package. Similarly in time we should use libtool.
There is nothing really blocking progress here, but the initial version
just mimics what we …
> Scripts: Start of autotools bootstrap.

- m3-libs/m3core/src/coroutine/Common/Coroutine.i3
- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.i3
- m3-libs/m3core/src/coroutine/UCONTEXT/CoroutineUcontext.m3
There are two ways to do this:
- Continuation passing style -- call instead of return; that
is done here.
- Continuation passing style-lite; similar, but
all the C code would do is allocate a local and pass its
address and size to Modula3. Modula3 would then memmove.
The result would be generally easier to understand
and can be presented separately.
The downside of this approach is that it is less general.
The more general approach is arbitrary code move around
between arbitrary functions, and a series of calls
that are logically tail calls.
The first solution is only about hiding the size of structures.
Also notice the const-ness of the memmove size.
> m3core: Coroutines: remove the need for one function to try to allocate stack space for another function.

- m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadApple.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadFreeBSD.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/thread/WIN32/ThreadWin32C.c
It is about as well to just check the direction of the given range.
Restore checking of register context, especially on grow-up stack.
Use alloca for stack pointer instead of address of local, to
better tolerate inlining. Platforms for which alloca is heap
instead of stack will "silently" not work -- they will likely
be very slow and/or free live data.
Put jmpbuf consistently in struct.
Gradually use unwrapped standard memset(0) idiom.
> m3core: Remove most checks of stack growth direction.

- m3-libs/m3core/src/thread/WIN32/ThreadWin32C.c
Sort includes alphabetically.
Remove unused define M3_FIELD_SIZE.
> m3core: Include malloc.h to _alloca compiles.

- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
InitC does not use its parameter.
> m3core: Remove residue of stack direction detection.

- m3-libs/m3core/src/thread/PTHREAD/ThreadApple.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/thread/WIN32/ThreadWin32.i3
- m3-libs/m3core/src/thread/WIN32/ThreadWin32C.c
- m3-sys/cminstall/src/config-no-install/Unix.common
m3core: Adapt garbage collection to IA64 that has a second 
stack for register window flushing that grows up.
Only HP-UX is implemented due to machine/documentation availbility.
VMS, NT (Windows 7?), Linux, and maybe old FreeBSD would be nice.
Prior, we captured registers and flushed windows after sem_post
and before sigsuspend. The register capture seems unnecessary,
given we have a signal context, and the flush seems too late.
The capture is also outside of the stack.
In this change the capture is eliminated for non-SPARC/IA64
and the capture and flush is moved to before sem_post.
Turn off dynamic linking for HP-UX as the config is not correct for
no-gcc linker driver, and I am kinda tired of dynamic linking woes.
Though HP-UX does support $ORIGIN.
With this IA64_HPUX64 is self-hosting, …
> m3core: Adapt garbage collection to IA64 (HP-UX).

- m3-comm/tcp/src/common/IP_c.c
- m3-comm/udp/src/Common/UDP_c.c
HP-UX defines socklen_t to size_t always, but then
uses socklen_t or int depending on defines.
> HP-UX: Fix more socklen_t to m3c_socklen_t.

- m3-sys/m3back/src/M3C.m3
Instead of typename and reinterpret_cast.
It seems both of these are needed for older OSF compiler
and that is ok. The template should maybe be removed (see AllocateTemps).
C++ is most desirable, by far, for portable optimized exception handling.
It *might* be desirable for other niceties like { }, C99
locals at not-top of scope before 99, math/fenv, bool, inline, etc.
> m3c: Use class and C-style casts.

- m3-sys/m3back/src/M3C.m3
runtime error:
assert failed: self.left # NIL 
file "../src/M3C.m3", line 2185
> M3C: Fix assertion failure building I386_NT.

- m3-sys/m3back/src/M3C.m3
libm3\LongFloatExtras.m3.cpp(803,57): warning C4244:
'return': conversion from 'double' to 'INT64', possible loss of data
and other occurences.
> m3c: Squash Visual C++ warning 4244 double to int64 conversion possibly lossy.

- m3-sys/m3back/src/M3C.m3
Removing it broke stuff or at least exposed a problem.
Revisit later.
Revert "M3C: Fix assertion failure building I386_NT. (#824)"
This reverts commit 4a95c8840cede9149493f2cdedf985e8d66a02ed.
Revert "m3c: Remove m3_loophole. (#823)"
This reverts commit 226cfc079b0ef9d0645a4a058533952b7b0c23a3.
> Restore m3_loophole template.

- m3-sys/m3back/src/M3C.m3
D:\a\cm3\bootstrap\m3back\M3x86.m3.cpp(6884,1): warning C4146: unary
minus operator applied to unsigned type, result still unsigned
> m3c: Disable warning 4146 unary minus is still unsigned.

- m3-libs/m3core/src/unix/Common/Uconstants.c
They are not used in cm3 tree and are here only
for historical/convenience reasons, to support Unix-specific
Modula-3 code outside the cm3 tree, which might not exist,
but people complained when I trimmed this stuff down to only
what cm3 uses.
https://github.com/modula3/cm3/discussions/833
> Haiku: Do not require F_GETOWN and F_SETOWN.

- m3-sys/m3tests/src/p2/p211/C.c
C.c:103:56: error: expression result unused [-Werror,-Wunused-value]
printf("string not found %s/n", (Type ? "double" : "float", String));
> tests: Fix p211 to compile, warning/error unused value.

- m3-libs/m3core/src/unix/Common/Usocket.c
Likely most of the asserts are not needed.
Likely all of them can be removed, perhaps with a little work.
> Haiku: Weaken static assertions about socket types.

- m3-libs/m3core/src/C/Common/CerrnoC.c
- m3-libs/m3core/src/C/Common/CstdioC.c
- m3-libs/m3core/src/Csupport/dtoa.c
- m3-libs/m3core/src/Csupport/hand.c
- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/runtime/common/RTProcessC.c
- m3-libs/m3core/src/thread/Common/ThreadInternal.c
- m3-libs/m3core/src/thread/POSIX/ThreadPosixC.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadApple.c
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
- m3-libs/m3core/src/time/POSIX/DatePosixC.c
- m3-libs/m3core/src/time/POSIX/TimePosixC.c
- m3-libs/m3core/src/unix/Common/Uconstants.c
- m3-libs/m3core/src/unix/Common/Uexec.c
- m3-libs/m3core/src/unix/Common/Ugrp.c
- m3-libs/m3core/src/unix/Common/Uin.c
- m3-libs/m3core/src/unix/Common/Unetdb.c
- m3-libs/m3core/src/unix/Common/UnixC.c
- m3-libs/m3core/src/unix/Common/UnixLink.c
- m3-libs/m3core/src/unix/Common/Usocket.c
- m3-libs/m3core/src/unix/Common/UstatC.c
- m3-libs/m3core/src/unix/Common/UtimeC.c
It is not a terrible idea, but:
- I disabled it a few months ago. Nobody was bothered.
- It is a small mess in the code.
- It is not "portable"..but it is widely supported by gcc, clang, msvc.
- I disabled it because it was not being used consistently,
or _perhaps_ correctly. The inconsistencies were found
by concatening all the files ("single file bootstrap").
- While there is value in reducing dynamic link metadata,
it does not seem super valuable to focus on the small amount o
hand written C++. It is more interesting to handle things in the compier maybe.
- There might be yet other ways to handle this, though they
are not super likely to be implemented any time soon: lists
of functions linker-specific text files, like Msvc .def; again
nicely done for most code in compiler, but again …
> m3core: Remove M3_DLL_EXPORT M3_DLL_IMPORT M3_HAS_VISIBILITY etc.

- m3-libs/m3core/src/unix/Common/Usocket.c
M3 does not have to be larger. They can be the same size.
Amend nearby comment.
Obviously this should be cleaned up. We have the same asserts 3 times.
> Haiku: Correctly weaken asserts about sun_path.

- m3-libs/libm3/src/uid/POSIX/MachineIDPosixC.c
- m3-libs/m3core/src/m3core.h
- m3-sys/cminstall/src/config-no-install/AMD64_HAIKU
- m3-sys/m3back/src/M3C.m3
- scripts/python/boot1autotools.py
- scripts/python/pylib.py
- GET_PC
- MachineIDPosix is one of the preexisting ones and add Python uuid.getnode() test.
- minimal config w/o dynamic linking to Modula3 code
- boot1 and boot1autools (redundant)
- Rework __cdecl/__stdcall slightly to avoid many warnings.
This might need revisiting for Haiku/x86.
- Remove putw/getw under ifdef.
- Skip context.h under ifdef.
- Some networking static_assert fixes went in prior.
- Errno fixes went in prior.
This is enough for boot1autotools.py amd64_linux to build cm3 and not find cm3.cfg, a typical milestone.
Thanks to DKnoto for nudging this along.
https://github.com/modula3/cm3/discussions/833
> Haiku/amd64 support.

- m3-libs/m3core/src/m3core.h
- m3-sys/m3quake/src/MxConfigC.c
I386_HAIKU says architecture is "BePC".
Just return M3_HOST and skip uname.
The entire uname path is mostly a waste.
This entire function is mostly a waste.
We can skip uname via ifdef, but sometimes endian is not clear,
and uname lets us stop maintaining per-system code.
i.e. now that M3_HOST has been show to checkout against uname,
we can remove M3_HOST and only use uname.
Both mechanisms remain though, to continue testing.
We can skip this function (MxConfigC__HOST) entirely once config is "auto" or "cmake" or "autotools".
When the notion of a multi-arch install is above bin/lib/pkg, instead of embedded in pkg.
Or when the output directory is "out" or "obj" our outside of the entire git tree and user
creates it arbitrarily.
MxConfigC__HOST exists just to default TARGET, but most …
> I386_HAIKU: Fix MxConfigC__HOST.

- scripts/python/pylib.py
And still Python2 (2.7).
File verified to be the same.
Code adapted liberally from concierge.py.
Except concierge.py trims one extra package (m3-ui\webvbt\src\hyperpage\src)
Presumably this is the last thing to fix so that scripts
work with Python2 and 3.
Haiku does not have Python2 at least in my install.
My HP-UX install does not have Python3 but it is likely possible.
> Scripts: Adapt MakePackageDB to work with Python3.

- m3-sys/cminstall/src/config-no-install/NT.common
- scripts/python/boot1.py
After making them with mklib and deleting it.
This is a step toward not using this functionality
in mklib, and writing the .def files elsewhere, either moving
the mklib code to cm3, or in m3front or m3back for exported functions,
possibly even discerning the three kinds: lowercase interface(.i3),
uppercase Interface(.i3), or no .i3 at all.
> NT config: Make static libs with native link /lib.

- scripts/python/pylib.py
Bootstrapping has evolved enough that we do not have to support old host cm3.
> scripts: No longer assume NT386 host from very old cm3.

- scripts/python/pylib.py
This could take many steps and remain unfinished.
Everyone by now should have switched:
LINUXLIBC6 => I386_LINUX
NT386 => I386_NT
NT386GNU => I386_CYGWIN    probably no user of former
NT386MINGNU => I386_MINGW  ditto
SOLsun => SPARC32_SOLARIS  possibly one line edit of config to favor Sun compiler
SOLgnu => SPARC32_SOLARIS  possibly one line edit of config to favor Gnu compiler
FreeBSD4 => I386_FREEBSD
Of course these are all 32bit so falling out of use as well.
> Drain legacy-named targets.

- scripts/python/pylib.py
Because the C backend passes the static link differently than gcc and integrated backends, is the rationale for that.
> pylib: Remove disabled notion of appending C to BuildDir.

- m3-libs/m3core/src/unix/Common/Uconstants.c
from 6f6564b39873a8fc917f45c90ca0ab85f1411836.
> m3core: Add semicolons after M3_STATIC_ASSERT.

- m3-sys/cminstall/src/config/NT.common.old
The intent is to make NT.common imply Visual C++
and remove Mingw and Cygwin stuff from it, such as their dynamic linking.
Also this will serve as a mklib backup though really
we might just delete it. Mingw/Msys/Cygwin can have separate configs, or fall under a future autotools/cmake default (which really all systems should be able to, including Visual C++).
> config: Save NT.common as NT.common.old.

- scripts/python/boot1.py
i.e. Python3 incompatibilities.
Scripts continue to work with Python2 and Python3.
> Scripts: Fix list/filter problem, writing bytes vs. string, sorting dict_keys.

- m3-libs/m3core/src/unix/Common/UnixC.c
Otherwise we get the size of a file, read it, and fail because
the read size and stat size vary.
I wonder if we should use stdio i.e. fopen("rb") instead of unistd.h.
Problem is still some need for opendir/readdir/closedir and stat,
which are not in stdio.h
Also fcntl would use file no. Maybe no/little gain.
> djgpp: open and creat with binary mode.

- m3-libs/libm3/src/os/POSIX/FilePosix.m3
Error is -1, not any non-zero.
I noticed this debugging djgpp but it might not be enough there.
> libm3: Check error correctly from fcntl(F_SETFL).

- caltech-parser/cit_util/src/m3makefile
It is not used and does not link on Windows.
> caltech: Remove Chmod.

- m3-libs/libm3/src/os/WIN32/m3makefile
The matter could still use some investigation, as to why only sometimes
are multiple revelations of the same type noticed and cause errors.
Given a desire for converged win32/posix bootstrap or even full source I don't
love that pattern anyway. I'd rather switch in the C with ifdef
win32 than pick and chose m3 files, with stubs on the other side's dependencies,
until/unless there is another idea.
As well then user threads could be a command line parameter on systems that support user and not.
Win32 gui vs. X gui could be a command line parameter on Cygwin.
Pthreads vs. Win32 threads ditto.
system vs. spawn vs. fork/exec ditto.
etc.
> m3makefile: Remove old comment about adding Win32 on Cygwin.

- m3-libs/libm3/src/os/POSIX/FilePosix.m3
And so return RegularFile.FileType instead of Pipe.FileType.
> libm3: djgpp: Check if S_IFSOCK # 0.

- m3-libs/m3core/src/unix/Common/UnixC.c
This is to support NT/x86 with non-default compiler flags, maybe not worth the noise and hassle.
> m3core: Add some missing __cdecl.

- m3-libs/m3core/src/unix/Common/UstatC.c
This was sort of a problem for djgpp.
> m3core: In stat logging, include mode.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UstatC.c
This is closer to where djgpp problem was (since sock==0,
djgpp thought all files were sockets, i.e. pipes, and turning
on flags for IntermittenRead would fail since djgpp does not support nonblocking.)
> m3core: Add optional fstat logging, like stat.

- m3-libs/m3core/src/unix/Common/UnixC.c
Presumably this is breaking MacOS and was unintentional.
> m3core: Fix chdir tracing to be optional.

- m3-libs/m3core/src/unix/Common/UnixC.c
- m3-libs/m3core/src/unix/Common/UstatC.c
Restore lost wrapper for chmod.
> m3core/unix: Restore lost return from fstat.

- m3-sys/m3quake/src/M3Path.m3
- m3-sys/m3quake/src/MxConfigC.c
- m3-sys/m3quake/src/MxConfigC.i3
- m3-sys/m3quake/src/QMachine.m3
Allow colon for device/volume separator.
Allow forward and backward slashes.
Also Cygwin case insensitivity here.
Rework PathEqual using expression.
We have too much path handling code and it is likely all not right.
> djgpp/dos: Treat paths more like Windows (or vice versa).

- m3-libs/libm3/src/os/POSIX/m3makefile
- m3-libs/libm3/src/os/WIN32/m3makefile
- m3-libs/libm3/src/os/m3makefile
DJGPP paths are like c:/foo and maybe c:/foo\bar.
Win32 is that.
Posix is only /foo/bar.
> djgpp/dos: Use Win32 Pathname implementation.

- m3-sys/cminstall/src/config/I386_DJGPP
There a few things going on here.
- The use of autotools failed.
That should be looked into, but I did not.
- To workaround autotols not working,
I run the compiler etc. manually.
- There are many versions of gcc and g++ (gxx) for DJGPP.
Some work for me, some crash.
Rather than carefully only install working ones,
and rather than probe for all of them and which work,
this change calls cc1plus and as directly.
It appears able to build itself, slowly, but we might need to tweak linking still.
> MSDOS/DJGPP: Rewrite config.

- m3-sys/cminstall/src/config/I386_DJGPP
- Eliminate some duplication.
- Try gcc 4.94 before 10.
10 ran out of memory once.
4.94 usually works, but not always.
- Remove the path slash translation and escaping, probably not needed.
- Put in the noecho that people like. Use -commands to breakthrough.
- Remove comment to redo linking, since it worked.
The gxx driver is ok, it is its default cc1plus that crashes.
- Comment lack of sockets and gui. Both fixable but probably won't be.
- Fixup what is the source, i.e. copy to local. cpp, and add comments.
It is to one get language choice and output w/o switches, at least
if we ran driver.
cm3 can now build itself on MS-DOS.
> Config: djgpp tweaks

- scripts/upgrade.sh
- scripts/win/pkginfo.cmd
It was to accomodate old bad libs in very old distributions, replace them,
or missing libs in some Windows SDKs.
Building it has done nothing since March 2021 and was long prior obsolete.
> scripts: import-libs is no longer needed

- m3-sys/cminstall/src/config/I386_DJGPP
10 usually does work, though is also much larger than 3.46.
3.46 is really old.
> MS-DOS config: Try compilers newest to oldest.

- m3-libs/libm3/src/os/WIN32/PathnameWin32.m3
- m3-sys/cminstall/src/config/I386_DJGPP
Matches Posix and matches being reasonable.
now:
base(foo.cpp.obj) == foo.cpp
extension(foo.cpp.obj) == obj
prior:
base(foo.cpp.obj) == foo
extension(foo.cpp.obj) == cpp.obj
Fixes https://github.com/modula3/cm3/issues/937
Remove DOS config comment mentioning this bug.
Note that DOS is mostly Posix, but uses Win32 paths.
> libm3: Split extension at last dot (after slash), not first.

- scripts/python/pylib.py
There appears to be a notion of deleting config files from the bin
directory (vs. the bin/config directory). I do not remember
where this came from, but I suspect it was to repair a brief
mistake long ago. Remove it.
Larger goal is to cleanup python scripts some and elevate
out of python directory.
> scripts: No longer delete config files in bin.

- scripts/python/install-back.py
- scripts/python/pylib.py
I might come to regret this, but this is ongoing
removal of m3cc support from scripts\python,
esp. to trim scripts\python.
m3cc is supported by new concierge, and the .sh files,
and the scripts ultimately don't do much.
Three sets of scripts is excessive, for what
I do not use and does not support "a lot" of platforms.
> scripts: Remove ShipBack from python.

- scripts/python/pylib.py
Before deleting the config that reaches back to source tree,
put more of its MxConfig non-cm3 user support into the distribution form.
if not defined("CR") CR = "\n" end
if not defined("EOL") EOL = "\n" end
if not defined("M3_PROFILING") M3_PROFILING = FALSE end
if not defined("SL") SL = "/" end
vs. only
if not defined("SL") SL = "/" end
> scripts: Config updates.

- m3-libs/libm3/src/uid/POSIX/MachineIDPosixC.c
It does not appear to exist. Cygwin is kinda Windows, kinda Unix.
> Cygwin: Skip net/if_arp.h.

- m3-libs/libm3/src/uid/POSIX/MachineIDPosixC.c
- skip if_dl.h
- fix warning re cdecl
> Cygwin: Fix MachineIDPosixC.c test code.

- m3-libs/m3core/src/unix/Common/Uconstants.c
Make it conditional, like DJGPP.
Found this using Visual C++ 2008/x86.
> m3core: EWOULDBLOCK is not defined on older Windows.

- m3-sys/m3back/src/M3C.m3
This needs more work, but the answer is probably to depend on C99.
Most targets already do (Alpha/OSF being an exception).
See https://github.com/modula3/cm3/issues/962
Found this using Visual C++ 2008/x86, which will probably end up not supported.
> m3c: Temporarily expand llroundl workaround to Win32 not just Win64.

- m3-sys/m3quake/src/MxConfigC.c
Found this using Visual C++ 2008/x86 which
will probably end up not supported due to C99.
And the correct fix here will probably to add
cxx_source or cpp_source to m3build and rename all the .c files.
To be sure not to compile anything as C.
But also add back the /TP switch?
> m3quake: Fix MxConfigC.c for older compiler.

- m3-libs/m3core/src/unix/Common/UnixC.c
It is varargs. Cast the parameter.
> m3core: Be sure to pass mode_t to open.

- scripts/python/pylib.py
Granted almost all targets can use gcc backend.
> scripts/python: Move all targets to C++ backend.

- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.i3
- m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3
The problem is that ThreadPThread cannot import from Coroutine.
Doing so changes the initialization order. ThreadPThread must
initialize before Coroutine.
The solution is just to declare CoroutineSupported in ThreadPThread,
since it extern, it can be anywhere.
> m3core: Fix startup problem.

- m3-sys/cminstall/src/config/OpenBSD-old.common
Save -old, many years old.
Current systems supports origin
Fatal-warnings seem ok.
Add comments for odbc/postgres.
OpenBSD was crashing until recently but it is fixed. It was somehow the coroutine code in threads.
> OpenBSD config update.

- caltech-other/bool/src/misc.h
I am guessing, we do not actually ever need this.
> caltech OpenBSD: No malloc.h

- scripts/python/pylib.py
Before retiring it someone needs to compare
I386_NT w/ and w/o it more thoroughly, i.e.
the gui apps cube solataire tetris etc.
Solataire seems to have problems.
It resizes poorly upon start, at least.
> scripts/python: Restore some support for integrated backend.

- m3-libs/m3core/src/runtime/common/RT0.i3
- m3-libs/m3core/src/runtime/common/RT0.m3
- m3-libs/m3core/src/runtime/common/RTAllocStats.m3
- m3-libs/m3core/src/runtime/common/RTAllocator.m3
- m3-libs/m3core/src/runtime/common/RTCollector.m3
- m3-libs/m3core/src/runtime/common/RTHeapMap.m3
- m3-libs/m3core/src/runtime/common/RTHeapRep.i3
- m3-libs/m3core/src/runtime/common/RTHeapRep.m3
- m3-libs/m3core/src/runtime/common/RTHeapStats.m3
- m3-libs/m3core/src/runtime/common/RTutils.m3
The goal of this PR is to remove endian-specific code from cm3
and its constituent libraries.
The reason for that, is so that the output of the C++ backend
needed to produce cm3, is portable between little endian and big endian systems.
The goal eventually is to have one thing to download for any system, Unix, Windows,
32bit, 64bit, little endian, big endian, just like most "source".
This is tedious and arguably slightly reduces readabilty and performance
but it should not be significant either way.
> m3core: Remove bitfields from RT0.

- m3-libs/m3core/src/m3core.h
- m3-libs/m3core/src/unix/Common/UdirC.c
- m3-libs/m3core/src/unix/Common/UnixC.c
- m3-libs/m3core/src/unix/Common/UstatC.c
- m3-libs/m3core/src/unix/Common/Uuio.c
Anonymous structs are not portable. Call it s for struct.
Seen building on Solaris w/ Sun CC.
> m3core: Anonymous structs are not portable.

- m3-sys/m3quake/src/MxConfigC.c
Rename it arbitrarily to xsparc.
> MxConfig: sparc is a macro.

- m3-sys/m3front/src/exprs/TextExpr.m3
- m3-sys/m3front/src/misc/CG.m3
- TextExpr.SetUID: Write entire word instead of only 20 bits in a ref header.
- CG.Hdr_to_info: Write "little endian", which is really neutral.
Tested via boot1.py to SPARC64_SOLARIS and then boot2min.py which includes upgrade.py.
As well as usual little endian AMD64_NT upgrade.py.
Big endian was probably broken in the brief time since I removed RT0 bitfields.
Boot1.py little endian and big endian diffs are reduced but not quite gone.
Initialized bitfields (i.e. outside of cm3) should not be impacted, should still work.
More testing is to be done.
Little endian systems are not affected anyway.
> m3front: Endian neutrality.

- m3-sys/cminstall/src/config/Solaris.common
We should probably use sysconf(nproc) or such.
> Solaris config: parallel back

- m3-libs/libm3/src/m3makefile
- m3-sys/m3back/src/M3C.m3
When building boot, remove from libm3: random ui sortedtable pickle hash.
These use bitfields and are not needed in cm3.
In m3c replace sortedtable with table to avoid use of bitfields.
Normal libm3 is not affected by this.
Only when building with cm3 -boot.
We should probably split into multiple libs but probably will not.
> Endian neutrality: Trim libm3 for boot.

- m3-libs/m3core/src/float/Common/IEEESpecial.m3
- m3-libs/m3core/src/float/Common/grisu/IEEE.i3
- m3-libs/m3core/src/float/Common/grisu/IEEE.m3
- m3-libs/m3core/src/float/Common/grisu/m3makefile
- m3-libs/m3core/src/float/Common/m3makefile
- m3-libs/m3core/src/float/IEEE/LongFloatBoot.m3
- m3-libs/m3core/src/float/IEEE/RealFloatBoot.m3
- m3-libs/m3core/src/float/IEEE/m3makefile
- m3-libs/m3core/src/float/m3makefile
Introduce new ways to construct/deconstruct REAL / LONGREAL
that produce endian neutral C++, so that C++ bootstraps can be endian neutral.
There are two basic acceptable ideas:
- traffice in an unpacked record with sign, exponent, significand,
that will be larger than real/longreal.
- pass integer/longint around, or loopholed real/longreal and use
Word/Long.Insert/Extract in place of read/writing loopholed record fields,
and wrap Word/Long in things like GetExponent(r:REAL):INTEGEr, SetExponent(VAR r:REAL; exp: INTEGER).
The new functionality is adding to the existing IEEE module which was added for Grisu work.
Grisu parts are now sometimes compiled to C++ (the original reason to omit Grisu is likely
obsolete now and will be revisited later).
In some places rather than slow down normal …
> m3core: Endian neutrality.

- m3-sys/m3front/src/values/Variable.m3
Likely we could eliminate one of them?
> Endian neutrality: Widen Variable.mem_type and stk_type from 4 to 8 bits.

- m3-libs/m3core/src/float/Common/grisu/IEEE.m3
To fix range error, I thought I had seen and fixed this earlier sorry.
> Endian neutral: Adjust int32/int64 types in IEEE.

- m3-comm/events/src/EventStubLib.m3
- m3-comm/netobj/src/netobjrt/StubLib.m3
- m3-comm/netobj/src/tcpnetobj/HeaderOps.m3
- m3-comm/rdwr/src/SimpleMsgRW.m3
- m3-comm/tcp/src/common/ConnMsgRW.m3
- m3-libs/binIO/src/FastBinIO.m3
- m3-libs/libm3/src/hash/SHA256.m3
- m3-libs/libm3/src/uid/Common/Capability.m3
- m3-libs/libm3/src/uid/Common/TimeStamp.m3
- m3-libs/libm3/src/uid/Common/m3makefile
- m3-libs/m3core/src/m3makefile
- m3-libs/m3core/src/swap/Swap.i3
- m3-libs/m3core/src/swap/Swap.m3
So it might be used in float pack/unpack.
Change to function based interface instead of exposing global variable, which is challenging to dynamically link on Windows.
> Move Swap from libm3 to m3core.

- m3-sys/cminstall/src/config/I386_DJGPP
Config: On DJGPP something is inserting incorrect backward slashes in paths.
Workaround in config by changing them to forward slashes.
This should not be needed really.
Reported and based on proposed fix from Victor.
> Config: DJGPP convert backward slashes to forward.

- m3-libs/libm3/src/os/POSIX/m3makefile
Add TODO comments about unifying bootstraps by removing if in m3makefile,
at least in the part of the system that constitutes cm3.
> Add TODO comments about unifying bootstraps by removing if in m3makefile.

- m3-sys/cm3/src/version.quake
There is a perhaps corner case where
exec/try_exec use system
and q_exe uses Process.Create
system probably always uses sh
Process.Create uses sh in a fallback, depending on error.
Cygwin system is finding git
Cygwin Process.Create is not finding git
I am guessing there is rarely a difference?? But I don't know.
In my case, git.exe is the Windows git and I have no Cygwin git.
Installing Cygwin git could help.
The rest of the build create a lot of processes and works.
"For now", maybe forever, in version.quake, skip running git on Cygwin.
Probably nobody will notice.
I looked into changing Process.Create to fallback for another error (NOENT)
to /bin/sh. That should "fix" it. But not clear we should make that change there.
There is Cygwin-specific Process.Create (could be at runtime …
> Cygwin: Skip git info in version.quake.

- m3-sys/cminstall/src/config/Darwin.common
Fix "ld" warnings on Mac Os ( OS "Darwin")
i.e. fix
= =
+ld: warning: -multiply_defined is obsolete
+ld: warning: -bind_at_load is deprecated on macOS
+ld: warning: ignoring duplicate libraries: '-lSystem'
= =
> Fix "ld" warnings on Mac Os ( OS "Darwin")

- m3-libs/libm3/src/arith/POSIX/COPYRIGHT-INTEL
- m3-libs/libm3/src/arith/POSIX/Math.i3
- m3-libs/libm3/src/arith/POSIX/MathPosix.m3
- m3-libs/libm3/src/arith/POSIX/MathPosixC.c
- m3-libs/libm3/src/arith/POSIX/MathPosixC.i3
- m3-libs/libm3/src/arith/POSIX/m3makefile
See cm3 issue 1178.
This PR creates glue procedures for the Math routines cabs, frexp, and modf.  
signgam is left alone---I am not sure it needs any work.
What we do here is use standard call-by-value and standard C types to communicate in the simplest way into a new glue C module, with its own EXTERNAL symbols.
The suspect procedures are unmarked as EXTERNAL in Math.i3 and instead implemented in MathPosix.m3, which calls the new C code with appropriate arguments.
The code has been tested to link with all symbols, but not for functionality.  (Prior work does not link, at least not with the C backend.)
> Add glue code to fix missing Modula-3 implementations of cabs, frexp,
