README
m3-libs/m3core/src/unix/Common/Uugid.c

See the subject, as well as Issue #22 .

added some helpful info to the README and fixed a bug in Uugid.c

---

scripts/python/pylib.py

Alternative to https://github.com/modula3/cm3/pull/48.

Add support for Visual C++ 2017 and 2019, and assume unknown ones are 2015 or newer.

---

m3-sys/m3back/src/M3C.m3

_setjmp is declared incorrectly.
This particularly breaks NT targets such as AMD64_NT, using newer compiler (like since 2015).
You must include setjmp.h. You cannot declare setjmp yourself. It is a compiler intrinsic now.
If you don't, https://github.com/modula3/cm3/issues/47#issuecomment-496111380 is what happens.
todo: This change always includes setjmp.h and compilation is slow.
A later change should try to optimize that away.

Fix C backend: include setjmp.h instead of declaring setjmp.

---

caltech-other/bool/src/bool.c
caltech-other/bool/src/bool.h
caltech-other/bool/src/misc.c
caltech-other/bool/src/misc.h

- Add extern "C".
- Rename true and false to True and False.

caltech-bool: Convert to valid C++.

---

m3-sys/m3back/src/M3C.m3

I just regressed it (void vs. not_void), but nobody references
it this way in Modula-3. The uses all go via C wrappers.

C backend: Remove longjmp support.

---

m3-sys/m3back/src/M3C.m3

- fix typo in comment
- dial up debug level (should be command line parameter)
- TIntLiteral:
We had signed TInt:
commented out assert(x <= TInt.Max8);
commented out assert(x <= TInt.Max16);
commented out assert(x <= TInt.Max32);
I guess they failed for me in the past.
not commented out assert(x <= TInt.Max64);
It fails on big endian like PA32_HPUX, in LongRealRep.i3.
Change these all to unsigned TWord:
not commented out assert(x <= TWord.Max8);
not commented out assert(x <= TWord.Max16);
not commented out assert(x <= TWord.Max32);
not commented out assert(x <= TWord.Max64);
This merits more attention in the frontend.
Frontend I think plays fast and loose with signedness,
and likely all literals should be considered signed, but I don't know.
When asserts fail in TIntLiteral, be sure to …

C backend misc.

---

m3-sys/m3back/src/M3C.m3

The prior versions are not at all informative.
Still around 100 to improve but maybe this suffices for now.

M3C: Start making asserts more informative.

---

m3-win/vcredist.txt

Some of the old links no longer work.

vcredist: Provide updated links.

---

m3-comm/tcp/src/POSIX/IP.m3

fix leak in unusual error path. Initialize locals.

IP: Cleanup GetAddrInfo and free correct memory,

---

doc/help/gen_html/tcp/src/POSIX/Herrno.i3.html
doc/help/gen_html/tcp/src/POSIX/HerrnoC.c.html
m3-comm/tcp/src/POSIX/Herrno.i3
m3-comm/tcp/src/POSIX/HerrnoC.c

m3-comm: Remove Herrno_Set_h_errno; it is not used

---

m3-libs/m3core/src/m3core.h

typedef int BOOL;
define TRUE 1
define FALSE 0
Useful.

m3core.h: Provide BOOL/TRUE/FALSE.

---

m3-libs/sysutils/src/cm3/TextUtils.m3
m3-libs/sysutils/src/pm3/TextUtils.m3

Saving a heap allocation. Similar for Upper.

sysutils: If a string is all lowercase already, then return it directly from Lower.

---

m3-sys/m3middle/src/Target.m3

With that in mind, generalize the check for x86 to be:
starts with any of the following, case insensitive:
86 i86 x86 i386 i486 i586 i686
ends with any of the following, case insensitive:
86
Too broad?
Some people use names like i686 to imply instructions
not in the original i386. Some people define i386 to
mean any 32bit x86.
Ultimately m3middle/m3front ascribe very little
to this, just related to packing/alignment, when not generating C.

m3middle/Target.m3: There used to be the target "NetBSD2_i386".

---

m3-sys/m3back/src/Codex86.m3

Fix https://github.com/modula3/cm3/issues/58

m3back: Fix asserts that can fail when comparing int64.

---

m3-sys/m3back/src/M3C.m3

As long as it is easily printed. It is a bit verbose, granted.

m3c: More dumping into comments, of init_chars parameter.

---

m3-sys/m3back/src/M3C.m3

Rather than skipping entire strings with unprintable
or comment characters, replace those with dot.
m3c is too heap intensive alas.

m3c:Try harder to debug print init_chars.

---

m3-sys/cm3/src/Builder.m3

Backend mode was not being set.

m3c:Actually cleanup source paths to not have output directory.

---

m3-lectern/lecternclient/src/POSIX/LecternClient.c
m3-lectern/lecternclient/src/WIN32/LecternClient.c

I had missed implicit int before.

lectern: Convert K&R C to ANSI.

---

m3-libs/m3core/src/win32/WinGDIc.c

m3core windows: Fix and cosmetic.

---

m3-sys/m3back/src/M3C.m3

m3front is willing to issue an unconditional abort in the middle of start_call/call.
Upon which, it stops popping parameters.
This leads to errors from the C compiler, for calls with insufficient parameters.
Test p268 does this.
When we see this, evaluate whatever parameters we get, possibly before the abort, maybe that has visible
side effects, but skip the call.
Now p268 compiles.
Note that indirect calls in m3c are presently untyped.
This should apply there as well, but the C compiler would already accept what we had.
This assumes no continue after abort, which is a little debatable.
But we don't have enough parameters from m3front so we cannot very
well make the call. m3front ignores that you can continue from
faults in a debugger.
We should probably make this conditional on if we saw …

m3c: Allow invalid IR: direct calls with insufficient parameters

---

m3-sys/cminstall/src/config-no-install/Solaris.common
m3-sys/m3cc/src/gnucc.common
scripts/python/c_compiler

Solaris: Add more paths to Sun compilers.

---

m3-libs/m3core/src/C/Common/CsetjmpC.c

not longjmp. Longjmp is easy because call it from C.
Move extern C around just cosmetic.

setjmp: Fix comment: sigsetjmp is the linking problem, e.g. on Linux,

---

m3-comm/tcp/src/POSIX/TCPHackC.c

m3-comm:extern C again

---

m3-sys/m3back/src/M3C.m3

This change does a much better job of typing, though there is
more to do.
Specifically before, pointers to anything tended to just be:
typedef void* ADDRESS;
typedef ADDRESS Twhatever; where whatever is the typeid.
This included for example VAR parameters.
Now we do a much better job of making Twhatever point
to some other type. At least pointers to base types.
Records might need completion still.

m3c: Stronger typing.

---

m3-sys/m3linker/src/MxGen.m3

Replace `LPSTR` with `PSTR`.
Conditionalize declaration/import of `RTLinker.AddUnitImports`.
Remove empty function.

main: Add __cdecl and tweak newlines.

---

m3-sys/m3gdb/gdb/gdb/dwarf2read.c

It is not quite right. We do see small null and non-null pointers
and just ignore them. "Small" enough?
This is because we have such an old fork of gdb it does not handle
current Dwarf. It would be great to update or unfork.

m3gdb: Some reading of Dwarf symbols so that g++ -g _m3main.c works.

---

m3-libs/m3core/src/runtime/POSIX/RTSignalC.c

The reason for this is speculation that we should compute HOST
amidst the same code. If we don't just use uname.
A full static host is fairly tempting, except, that on Debian
uname.machine factors in the endian vagaries.
Which I don't want to figure out, or worse, name.
Therefore HOST should be computed statically in many cases, but not all.
i.e. when GetPC had good clear support, or mostly (sometimes word
size is ambiguous), but not in the cases where endian can vary.
i.e. endian is unambiguous for x86, amd64, mac/ppc, ia64, sparc, arm64, riscv, m68k, hppa, alpha.
Endian is ambiguous for mips, ppc, arm.
Support is missing for m68k.
Also anything we don't know we will fallback to uname.
We might fallback to uname for a lot.
Also the way NetBSD is handled here, nicely, we should fallback …

m3core: Refactor GetPC into a macro GET_PC and usually function GetPC.

---

m3-sys/m3back/src/M3C.m3

concatenating all the .c files for a package into one.
Otherwise struct definitions get duplicated and this is an error.

m3c: Put ifndef/define around struct definitions, to facilitate

---

m3-sys/m3cggen/src/Main.m3
m3-sys/m3middle/src/M3CG_Binary.i3
m3-sys/m3middle/src/M3CG_Binary.m3

This is useful beyond m3ccgen, will be shortly.

Move m3cggen.Map to M3CG_Binary, exposed via M3CGBinary.OpText(Op):TEXT.

---

m3-sys/m3back/src/M3C.m3

shorten define m3once_foo m3once_foo to define m3once_foo
The goal being to concat output and still be valid, so cm3 can be one file for easier redistribution and build.

m3c: More ifndef helper guards (fence, convert_int, etc.)

---

m3-sys/m3back/src/M3C.m3

There are typoed recursive types in the system:
TYPE FOO = REF FOO;
We reluctantly accept these since the rest of the system does.
When we see this, we attempt to break the loop
by just treating it as TYPE FOO = ADDRESS.
Luckily they are always self-referential.
We do not have:
TYPE FOO = REF BAR;
BAR = REF FOO;
which would take more work to detect.
We do in some sense detect these, by erroring, due to
a lack of forward progress, described below.
The detection was supposed be like:
if type.typeid == type.points_to_typeid
fallback to address
but was accidentally:
if type.typeid == type.typeid
which is always true.
This was in type.canBeDefined, not type.define.
This lead to calling type.define prematurely.
This lead to type.define falling back and typedefing
types to ADDRESS instead of …

m3c: Fix typo declaring pointers and resulting fallout.

---

m3-sys/m3back/src/M3C.m3

Subranges have colliding typeids. m3front bug?
For example:
libm3\Formatter.m3:
Int   = REF INTEGER;
ints: ARRAY [-256..256] OF Int;
declare_subrange typeid:T69A2A904 domain_type:T195C2A74 min:-256 max:256 bit_size:16
libm3\Sx.m3
MinBoxedInt   = -100;
MaxBoxedInt   = 100;
BoxedInts  := ARRAY [MinBoxedInt .. MaxBoxedInt] OF REF INTEGER {NIL, ..};
declare_subrange typeid:T69A2A904 domain_type:T195C2A74 min:-100 max:100 bit_size:8
Partial workaround it here by appending the size to the type text.
We could further workaround by deferring the typedef until use, as in this
case, neither type is used. Just defined.
This shows up if you concatenate all the files that make up cm3,
which is a goal for easier redist and build.

m3c: Tolerate duplicate typeids.

---

m3-sys/m3back/src/M3C.m3

This does not help all that much, i.e. for debugging.
It might help us remove casts on non-closure function pointer calls.
It is a step toward being able to concatenate m3c output
with all the .c files in the system, and distributing
cm3 as one .c file. Otherwise there are
errors e.g. regarding RTProcess__RegisterExitor.

m3c: Fill in ProcTypes.

---

m3-comm/netobj/src/NetObjTarget.i3
m3-comm/netobj/src/m3makefile
m3-comm/netobj/src/netobjrt/StubLib.m3
m3-libs/m3core/src/types/WideChar.i3

netobj: Move two lines from NetObjTarget to m3core:WideChar.i3

---

m3-sys/m3back/src/M3C.m3

This is so C and m3c output can be concatenated.

m3c: Add declare_typename implementation.

---

m3-libs/m3core/src/m3core.h
m3-libs/m3core/src/time/POSIX/DatePosixC.c

This should improve concatenating m3c output with C.

m3core: Rename Date_T to m3core_DatePosix_T.

---

m3-libs/m3core/src/m3core.h
m3-libs/m3core/src/time/POSIX/DatePosix.i3

DatePosix: Narrow some fields from INTEGER to int.

---

scripts/dev/windows/do-cm3.cmd
scripts/install/windows/cm3CommandShell.CMD

RCC_upgradeCM3_Win10_Fix

---

scripts/dev/windows/do-cm3.cmd
scripts/install/windows/cm3CommandShell.CMD

scripts: Update some .cmd files for Windows 10.
Redo https://github.com/modula3/cm3/pull/398 but with squash (arguments all around).

scripts: Update some .cmd files for Windows 10.

---

scripts/pkginfo.txt

I will likely use it shortly in m3c.

pkgs: add bitvector to front

---

scripts/examples/make-compiler.cmd
scripts/examples/make-compiler.sh
scripts/pkginfo.txt
scripts/python/make-dist.py
scripts/python/pylib.py
scripts/python/upgrade.py
scripts/upgrade.sh
scripts/win/upgrade.cmd

A dependency on this is likely to appear soon.

scripts: Add set to front.

---

m3-sys/m3front/src/values/Variable.m3

(Or was there a recent for the name, correlated to Tipe.i3 vs. Type.i3?)

m3front:Variable "tipe" to "type" rename.

---

m3-sys/m3front/src/types/Type.m3

Just "do not yet repeat yourself", factor out repeating code into functions.

m3front: Cleanup Type.{Strip,StripPacked,Base}.

---

m3-sys/m3front/src/types/Type.m3

In case something needs not to lower.

m3front: Type.IsStructured support Named types.

---

m3-sys/m3back/src/M3C.m3

(in m3c itself, no impact on its output)

m3c: Remove unnecessary brands.

---

m3-sys/m3front/src/types/Type.m3

It is maybe slower, but maybe not measurably and seems
slightly cleaner this way.

m3front: Make more StripPacked calls unconditional.

---

m3-sys/m3front/src/types/ArrayType.m3

m3front: ArrayType.Reduce call StripPacked unconditionally.

---

m3-sys/m3front/src/types/EnumType.m3
m3-sys/m3front/src/types/OpaqueType.m3
m3-sys/m3front/src/types/PackedType.m3
m3-sys/m3front/src/types/ProcType.m3
m3-sys/m3front/src/types/RecordType.m3
m3-sys/m3front/src/types/RefType.m3
m3-sys/m3front/src/types/SetType.m3
m3-sys/m3front/src/types/SubrangeType.m3

Most of these seem like they should be StripPacked.

m3front: Reduce partial inlining of Type.Strip.

---

m3-sys/m3back/src/M3C.m3

They don't yet full work. For example with generics.

m3c: Disable qidtext.

---

m3-sys/cm3/src/M3Loc.i3
m3-sys/cm3ide/src/utils/ID.i3
m3-sys/m3front/src/misc/Jmpbufs.i3
m3-sys/m3front/src/types/ProcType.m3
m3-sys/m3front/src/types/RefType.m3
m3-sys/m3front/src/values/Module.i3
m3-sys/m3front/src/values/Module.m3
m3-sys/m3front/src/values/Procedure.m3
m3-sys/m3loader/src/M3LoaderObj.i3
m3-sys/m3tools/src/M3Const.m3
m3-sys/m3tools/src/M3Parse.m3

And then change several:
x: M3ID.T := M3ID.NoID
to x := M3ID.NoID
Also some x: M3ID.T := 0 to same.
Though I am partial to unabstracted 0.
I kinda think the type really should be INTEGER or LONGINT but I did not change that.

Fix the type of M3ID.NoID to be M3ID.T.

---

m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c

To keep an array live on the stack, make it volatile, and access it at certain times.
Mark some functions to avoid inlining.
More likely this code should keep stuff on the stack,
by passing its address to another function, rather than
returning. Need test code to really change it though.

m3core: More convincing coroutine code.

---

m3-sys/m3front/src/values/Formal.m3
m3-sys/m3front/src/values/Variable.m3

One of these might be a recent regression.

m3front: Initialize some locals.

---

m3-sys/m3back/src/M3C.m3

- Reenable declare_typename.
- In declare_{pointer,indirect}, the new typehash
is typedefed to target* (often a name instead of a hash)
and is then rendered as target* instead of hash.
(Perhaps the typedef is redundant, consider removing it later.)
Refactor/rename how typename shares with {pointer,indirect}.
Rename "points_to" to "refers_to" to try to capture the commonality.
Introduce the base PointerOrTypename_t to Pointer_t and Typename_t
to capture the common _canBeDefined.
For _define they had very little code in common, like one
or two lines, so do not share.

m3c: Significantly improve declare_{pointer,indirect,typename}.

---

m3-sys/m3back/src/M3C.m3

m3c: Change M3ID.T to Name.

---

m3-sys/m3back/src/M3C.m3

This partially reverts commit 654aacbdd1929538f54c26e11fa5662222d8b089.
Only in m3c. The m3core change is ok.
The m3c change is insufficient because of confusion around unsigned types.
We get:
declare_typename INTEGER Cstddef_ssize_t ok
declare_typename INTEGER Cstddef_size_t not ok
Something else will hopefully succeed.

Parially revert "m3c / m3core: Repair integer types. (#533)"

---

m3-sys/m3back/src/M3C.m3

We get
declare_typename(INTEGER, "ssize_t") ok
declare_typename(INTEGER, "size_t")  wrong
The same type cannot be both signed and unsigned.
Typenames become the names for the underlying type,
and due to typenames occuring in inconsistent order,
this leads to errors, when you combine m3c output
with hand written C (m3core.h).
The workaround is to have m3c try to know
all the incorrectly specified types, and when seen,
do not replace the underlying type's name with them.
Another fix might be to ensure all parameters (locals? globals?)
have typenames, and then the names of types without context
would never be used. This is mostly the case now, but for synthesized functions.
We should consider eliminating unsigned types from use,
esp. uint64 on 64bit, and uint32 and uint64 on 32bit.
Given C …

m3c: Workaround unsigned type problems.

---

m3-libs/m3core/src/unix/Common/Usocket.i3

For consistency between m3c and C.

m3core: Usocket: int to const_int

---

m3-libs/m3core/src/unix/Common/Umman.i3

m3core: Umman: Change int to const_int.

---

m3-sys/m3front/src/misc/CG.m3
m3-sys/m3front/src/types/NamedType.m3
m3-sys/m3front/src/types/ProcType.m3
m3-sys/m3front/src/types/RefType.m3
m3-sys/m3front/src/types/Type.m3
m3-sys/m3front/src/values/Formal.m3
m3-sys/m3front/src/values/Variable.m3

which is under RTParams (command line @M3...)

m3front: Add some printing, under if debug

---

m3-sys/m3front/src/values/Variable.m3

It is nearly identical code, factor it better to reduce repitition.

m3front: Variable.Declare refactor slightly indirect param vs. direct.

---

m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c

It turns out size_t is not always pointer sized,
though maybe it does not matter.

coroutine: Move around the casts and the assumptions of integer sizes.

---

m3-sys/m3back/src/M3C.m3

i.e. new variables
debug_verbose := RTParams.IsPresent ("m3c-debug-verbose")
debug_types := RTParams.IsPresent ("m3c-debug-types")
debug := RTParams.IsPresent ("m3c-debug")
debug_comment_stdio := RTParams.IsPresent ("m3c-debug-comment-stdio")
debug_comment := debug_comment_stdio OR debug_types OR debug OR debug_verbose OR RTParams.IsPresent ("m3c-debug-comment")
This both is a long overdue cleanup, and is prelude to much more than would have made it worse.

m3c: Make verbosity controllable from command line, and drastically decrease defaults.

---

m3-sys/m3back/src/M3C.m3

- Work them into the graph walk of gradual type revelation.
What happens, is, like structs are forward declared right away.
Enums are defined about right away (their underlying types
being available about right away).
Struct as their constiuent field's types are defined.
Indirect types are defined as their base is defined, etc.
Previously typenames were not in this framework at all.
We just typedefed them right away, which does not work.
Maybe m3front could do things in a different order, alas.
Though it generally appears to. todo?
- As part of that, handle base types (int32, int64, etc.)
more within the framework, giving them hashed names
first, then typenames. We really want type names for friendly
output, but this serves to go through the required motions
of setting up the data …

 m3c: Bring back typenames.

---

m3-sys/m3back/src/M3C.m3

m3front defines it well enough.

m3c: Do not define LONGCARD specially.

---

m3-libs/m3core/src/m3core.h
m3-libs/m3core/src/unix/Common/Upwd.i3

But is this interface portable?

m3core: Fix Upwd to match between m3c and C.

---

m3-libs/m3core/src/unix/Common/Ugrp.i3

m3core: Add const in getgrnam.

---

m3-sys/m3back/src/M3C.m3
m3-sys/m3front/src/values/Module.m3
m3-sys/m3front/src/values/Procedure.m3

Somehow this was missed earlier.
What happens then is we get roughly:
Region.i3:
PROCEDURE ToRects():REF ARRAY OF Rect
no typename, no typeid, just cgtype => ADDRESS
Region.m3:
TYPE RectList = REF ARRAY OF Rect;
PROCEDURE ToRects():RectList
=> RectList
and RectList is strongly typed otherwise,
does not match ADDRESS, so if you compile
these together with the C compiler you get an error.
This change fairly simply passes the typeids.

m3front and m3back: Pass return typeids.

---

m3-libs/libm3/src/uid/Common/MachineIDC.i3
m3-libs/m3core/src/m3core.h

Fix combining m3c output with hand written C

libm3: MachineID__CanGet takes unsigned_char_star, not ADDRESS

---

m3-sys/m3linker/src/MxGen.m3

void* vs. char** (use incorrect void* to avoid changing signatures in m3core)
correct function pointer vs. incorrect function pointer (we have
to use incorrect due to type hash collisions)
So m3c output is combinable with C, i.e. _m3main.c

m3linker: Get RTLinker prototypes "correct".

---

m3-libs/m3core/src/Csupport/Common/dtoa.h

dtoa: Remove K&R support.

---

m3-sys/m3back/src/M3C.m3

of trying to declare them correctly ourselves.
This fixes compiling as C++ with m3c and C concatented on Mac,
because the declarations really were not always correct
and conflict with m3core.h's include of string.h.

m3c: Call memcmp/memset/memcpy/memmove wrappers instead

---

m3-sys/cm3/src/Builder.m3

Initialize locals.
The local `plan` was initialized to 0, never otherwise written, then compared to 2.
Make comments more polite.
When backend mode will ignore main_m3cc, do not look it up, and do not warn about, just set it to false.

m3main.c: Remove new recurring warning and skip an unnecessary lookup.

---

m3-sys/m3back/src/M3C.m3

This will fix an error and warnings on Solaris and allow reverting recent workaround.

m3c: Add return to non-void functions that lack return.

---

m3-sys/m3back/src/M3C.m3

internal_begin_procedure is now named Locals_begin_procedure.

m3c: Mild repair some trace logging.

---

m3-libs/m3core/src/m3core.h
m3-libs/m3core/src/unix/Common/Usocket.c

void* vs. char* in socket code
ssize_t vs. INTEGER in socket code
Add disable/enable switching.

m3core: Windows C++

---

m3-sys/m3front/src/types/ProcType.m3
m3-sys/m3front/src/values/Procedure.m3

m3front: Some debugging -- RTIO.Put if command line enables.

---

m3-sys/mklib/src/Main.m3

Modula-3 does not correctly access imported data.
Also do not log differently bss vs. not.
This cuts AMD64_NT m3core exports from 4265 to 1528,
many of which I had added (WinConstants.c) and global
variables in ThreadWin32.
This is still more than really should be exported but it is progress.
i.e. We should export that which is defined in .i3 files,
not internals from .m3.
Assert Keeper since it should have been checked prior.

mklib: Only export functions, not data.

---

m3-sys/cminstall/src/config-no-install/ALPHA_OSF

config: OSF: Remove configure_c_compiler.

---

m3-sys/cminstall/src/config-no-install/ALPHA_OSF

I believe this is what Modula-3 really wants.

config: osf: Use dynamic floating point rounding.

---

scripts/python/pylib.py

scripts: Python2 to Python3 conversion.

---

m3-sys/cm3ide/src/nodes/Source.m3

Minor fixes in cm3ide nodes/Source.m3

Minor fixes in cm3ide nodes/Source.m3

---

m3-sys/m3back/src/M3C.m3

This is an attempted fix of #749
Since the frontend ignores signs when asking the code generator to
produce static initializers, this patch intercepts those calls to
ensure they will compile in C.
"C backend" here means the generated C++ code that gets fed to an *external* g++, and not the integrated gcc fork.
It's tough to say if this patch is "correct".  It builds itself, it builds all the things, and it builds the new SHA256 module that exposed this bug.  But if there's a compiler test suite somewhere, I haven't found it yet.
It may be difficult to verify this patch on HEAD, because if you have already pulled in the new SHA256 module and have the broken compiler, it won't bootstrap.  I recommend reverting to something pre-SHA256, building the C backend with this patch, and then rolling …

fix declared type of static initializers in C backend

---

.github/workflows/mingw-integration-from-binary.yml

some changes in mingw-integration-from-binary.yml

for_CI-CD: swith CM3BUILD to cm3-min-AMD64_MINGW_66914fc

---

m3-sys/llvm/llvm13/src/Main.m3

Add AMD64_NT to llvm13

---

scripts/python/pylib.py

Remove some commented out code.
Combine FreeBSD, OpenBSD, NetBSD into bsd.
Remove unused then freebsd, openbsd, netbsd, thirtytwo, sixtyfour.

Scripts: Slight cleanup.

---

scripts/python/pylib.py

Remove handling of m3cc and integrated backend.

Scripts: Bootstrap only via C++ backend.

---

scripts/python/boot1.py
scripts/python/boot1many.py
scripts/python/boot2.py
scripts/python/boot2min.py
scripts/python/capture-boot.py
scripts/python/chext.py
scripts/python/do-cm3-all.py
scripts/python/do-cm3-min.py
scripts/python/do-cm3-std.py
scripts/python/do-pkg.py
scripts/python/install-back.py
scripts/python/install-cm3-compiler.py
scripts/python/install-config.py
scripts/python/install-front.py
scripts/python/make-deb.py
scripts/python/make-dist-cfg.py
scripts/python/make-dist.py
scripts/python/make-msi.py
scripts/python/pylib.py
scripts/python/pylib1.py
scripts/python/upgrade.py

So stop asking for python2, accept either.
Longer term we may want to rewrite the Python in C++98 or such
as that seems to be a much more long lasting platform, in terms
of compatibility and supported underlying systems. Or Quake
or Modula-3, though with some sort of bootstrap.

scripts: Python3 seems to work now.

---

scripts/python/boot2.py
scripts/python/boot2min.py

Move away from python2 while still working with it.

scripts: Modify python .exe that is looked for.

---

m3-sys/cminstall/src/config-no-install/IA64_HPUX32
m3-sys/cminstall/src/config-no-install/IA64_HPUX64

So use some full paths.
Possibly this is a problem with my install.

HP-UX Config: Linker looks for libFoo.so but not libFoo.so.1.

---

m3-sys/m3back/src/M3C.m3

Replace with an inline expression, with a temporary.
Attempt to simplify store, but casts are needed due to
unrelated pointer types both being just cgtype.addr.
Change store_helper to push an expression.
Existing few callers needing a statement can follow
with a call to new function eval (aka statement).
C++ is a good target, for optimized portable exception handling (which we do not have yet).
It is not needed for this case.

m3c: Remove m3_loophole.

---

scripts/python/pylib.py

- Add -MD flag that no longer fails on AMD64_NT.
- Remove -Fo.
- Make cross-NT logic instead of per-config, so
that covers ARM32_NT and ARM64_NT too.
- O2 and LTCG (link time codegen)
- delayload
- link -opt:ref
- Fix I386_NT to actually work.
- ResponseFile which is sometimes required (m3build should work this way).
- Batching (m3build should work this way).
This does veer from what m3build produces.

scripts: Fix and tweak historical NT bootstraps.

---

m3-sys/m3back/src/M3C.m3

m3c: Inline extract.

---

m3-sys/m3back/src/M3C.m3

And consider predeclaring even fewer.

m3c: Predeclare fewer types.

---

scripts/python/pylib.py

Scripts: More Python3 compatibility, filter is not indexable

---

m3-sys/m3quake/src/QMachine.m3

This is much less code and it is hoped but not known to
help make Cygwin backend be multithreaded.

m3quake: Replace Process.Create with Cstdlib.system.

---

scripts/python/boot1.py

boot1: Fix regression since moving out of pylib.py.

---

m3-libs/m3core/src/thread/POSIX/ThreadPosix.i3
m3-libs/m3core/src/thread/POSIX/ThreadPosix.m3
m3-libs/m3core/src/thread/POSIX/ThreadPosixC.c
m3-libs/m3core/src/thread/POSIX/test_dos_threads.cpp

Based on working proof of concept.
We still crash in QCompiler__CompileFile though.

Djgpp: Fill in more convincing thread implementation.

---

caltech-other/voronoi/src/output.c

fix: replace bitwise & with logical one

---

caltech-other/bool/src/bool.c

fix: comparison of integer expressions of different signedness

---

m3-libs/m3core/src/m3core.h
m3-libs/m3core/src/unix/Common/UdirC.c
m3-libs/m3core/src/unix/Common/UnixC.c
m3-libs/m3core/src/unix/Common/UstatC.c
m3-libs/m3core/src/unix/Common/Uuio.c

i.e. for debugging DJGPP port.

m3core/unix: Add simple disabled tracing.

---

m3-sys/cm3/src/Utils.m3
m3-sys/dll2lib/src/LibFile.m3
m3-sys/m3quake/src/QMachine.m3
m3-sys/mklib/src/Main.m3

Disambiguate error messages that say "unable to close".

---

m3-libs/m3core/src/unix/Common/UnixC.c

m3core: Rename parameter from close(a) to close(fd).

---

m3-sys/m3back/src/M3C.m3

Since people are asking about performance.
- We used to always initialize all locals.
This did seem to maybe mask bugs in the Modula3 code,
so we might now be exposing some. Might.
- initialize backend produced temporaries
- initialize structs ("for now")
- initialize variables that *seem* to be read before written
The analysis is flow-ignorant.
The analysis is knowingly wrong otherwise.
The variables are bitfields, widened to integers.
The entire variable is read, in order to write bits.
And then later only read those bits. The initialized bits
are read but never really used.
In future we should model Modula3 bitfields as C++ bitfields,
and largely removing insert/extract from the IR (still ok for Word interface,
but not for packed).
This new pass, ReadBeforeWrite, is integrated with …

m3c: Only sometimes initialize locals.

---

scripts/concierge.py

I noticed this installing on Win8.1 x86.

Concierge: Translate x86 to i386.

---

m3-libs/m3core/src/thread/POSIX/ThreadPosixC.c

mprotect is built on DPMI 1.0.
DPMI 1.0 is rarely implemented.
DPMI 0.9 is more common.
When we mprotect the pages at the end of thread stacks,
this works under plain MS-DOS with presumably cwsdpmi.exe
but it fails under Windows (98SE). Ignore it for MS-DOS only.
Fix compile of user threads for not-DJGPP.

DOS: Conditionally ignore mprotect of user thread stack ends.

---

scripts/python/boot1.py
scripts/python/boot1autotools.py
scripts/python/install-cm3-compiler.py
scripts/python/install-config.py
scripts/python/pylib.py

from 275c28f39876d48263dd0d8cf8a49bd3e678960b 7321f603a5e8d2f5996a94563906823b7a0b893d

scripts: Fix regressions.

---

scripts/concierge.py

map_os: if startwith openbsd e.g. openbsd7

Concierge: Fix OpenBSD detection.

---

m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c

Comment that there are basically two stacks, on ia64.
Accept two stacks w/o ifdef.
Check direction for both stacks (do not assume direction of ia64 second stack).
Remove excess asserts (esp. ignore null, but also that contains context).
Process second stack even if first stack absent, unlikely but simple.

ThreadPThreadC.c: Accept/ignore null.

---

m3-libs/m3core/src/coroutine/UCONTEXT/ContextC.c
m3-libs/m3core/src/thread/POSIX/ThreadPosixC.c
m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c
m3-libs/m3core/src/unix/Common/UdirC.c
m3-libs/m3core/src/unix/Common/UnixC.c
m3-libs/m3core/src/unix/Common/UstatC.c
m3-libs/m3core/src/unix/Common/Uuio.c

Alloca makes me a bit nervous.
Might compiler inline such functions, into loops?

m3core: Do not inline functions that use alloca.

---

m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3

This saves a heap allocation per thread.
The freeing of that heap allocation is failing on OpenBSD and maybe Cygwin.
Perhaps it is the victim of a bug elsewhere.

m3core: When not Coroutine.Supported () use old data structures.

---

m3-libs/m3core/src/thread/PTHREAD/ThreadPThreadC.c

On Linux valgrind wants the same signal we use for thread suspension.
Recall, signals are bad because there is no arbitration of them.
This is one example that proves the point.
To allow valgrind to work, rather than fail an assert in initialization,
try one lower signal upon failure.
We really need cooperative suspend, and then stop using signals entirely,
improving portability, debugability, etc.

m3core: Allow progress under valgrind on Linux.

---

m3-libs/m3core/src/thread/PTHREAD/ThreadPThread.m3

Now that the initialization order problem is fixed.
This is beautiful and "very" unsafe.

m3core: Reunify coroutine and non-coroutine paths.
